# 🧠 Mental Health Intelligence Platform

## Phase 1: Data Understanding

### Project Overview

This notebook focuses on understanding the unified OSMI Mental Health Survey dataset before any preprocessing or modeling.

The primary objective is to gain familiarity with the dataset, identify potential data quality issues, and establish a solid foundation for subsequent stages of the data science pipeline.

---

### Goals

- Understand dataset structure
- Explore each feature
- Identify missing values
- Detect duplicate records
- Understand feature distributions
- Evaluate data quality
- Document initial observations

> **Important:** No data cleaning or preprocessing is performed in this notebook.

## Import Required Libraries

The following libraries are used for data manipulation, visualization, and exploratory analysis.

In [2]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

plt.style.use("ggplot")

## Load Dataset

The unified dataset was created by combining multiple OSMI Mental Health Surveys across different years into a single standardized dataset.

In [3]:
df = pd.read_csv("../data/processed/unified_osmi_data.csv")

print("Dataset Loaded Successfully!")

Dataset Loaded Successfully!

## Dataset Preview

Before performing any analysis, let's inspect the first few records to understand the structure of the dataset.

In [5]:
df.head()

,source_file,survey_year,self_employed,no_employees,tech_company,primary_role_tech,benefits,know_options,formal_discussion,resources,anonymity,leave_ease,comfort_physical_mental,comfort_supervisor,discussed_with_employer,comfort_coworkers,discussed_with_coworkers,coworker_discussed_with_you,employer_importance_physical,employer_importance_mental,coverage_mental_health,know_resources,reveal_to_clients,reveal_to_coworkers,productivity_affected,productivity_percent_affected,have_prev_employers,prev_tech_company,prev_benefits,prev_know_options,prev_formal_discussion,prev_resources,prev_anonymity,prev_comfort_physical_mental,prev_comfort_supervisor,prev_discussed_with_employer,prev_comfort_coworkers,prev_discussed_with_coworkers,prev_employer_importance_physical,prev_employer_importance_mental,currently_disordered,diagnosed_disorder,disorder_anxiety,disorder_mood,disorder_psychotic,disorder_eating,disorder_adh_add,disorder_personality,disorder_ocd,disorder_ptsd,disorder_stress_response,disorder_dissociative,disorder_substance_use,disorder_addictive,disorder_other,past_disorder,sought_treatment,family_history,interference_when_treated,interference_when_not_treated,observations_less_likely_reveal,share_with_friends_family,bring_up_physical_interview,bring_up_physical_why,bring_up_mental_interview,bring_up_mental_why,openly_identified,identified_affected_career,identified_affected_how,team_reaction_if_knew,observed_unsupportive_response,unsupportive_response_desc,observed_supportive_response,supportive_response_desc,industry_support_rating,improvement_suggestions,additional_comments,willing_to_interview,age,gender,country_live,state_live,race,country_work,state_work
0,2014,2014,NaN,6-25,Yes,NaN,Yes,Not sure,No,Yes,Yes,Somewhat easy,Yes,Yes,No,Some of them,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,No,Often,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2014,2014,NaN,More than 1000,No,NaN,Don't know,No,Don't know,Don't know,Don't know,Don't know,Don't know,No,Maybe,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,Rarely,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014,2014,NaN,6-25,Yes,NaN,No,No,No,No,Don't know,Somewhat difficult,No,Yes,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,Rarely,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2014,2014,NaN,26-100,Yes,NaN,No,Yes,No,No,No,Somewhat difficult,No,No,Yes,Some of them,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,Often,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014,2014,NaN,100-500,Yes,NaN,Yes,No,Don't know,Don't know,Don't know,Don't know,Don't know,Yes,No,Some of them,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,Never,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.sample(10)

,source_file,survey_year,self_employed,no_employees,tech_company,primary_role_tech,benefits,know_options,formal_discussion,resources,anonymity,leave_ease,comfort_physical_mental,comfort_supervisor,discussed_with_employer,comfort_coworkers,discussed_with_coworkers,coworker_discussed_with_you,employer_importance_physical,employer_importance_mental,coverage_mental_health,know_resources,reveal_to_clients,reveal_to_coworkers,productivity_affected,productivity_percent_affected,have_prev_employers,prev_tech_company,prev_benefits,prev_know_options,prev_formal_discussion,prev_resources,prev_anonymity,prev_comfort_physical_mental,prev_comfort_supervisor,prev_discussed_with_employer,prev_comfort_coworkers,prev_discussed_with_coworkers,prev_employer_importance_physical,prev_employer_importance_mental,currently_disordered,diagnosed_disorder,disorder_anxiety,disorder_mood,disorder_psychotic,disorder_eating,disorder_adh_add,disorder_personality,disorder_ocd,disorder_ptsd,disorder_stress_response,disorder_dissociative,disorder_substance_use,disorder_addictive,disorder_other,past_disorder,sought_treatment,family_history,interference_when_treated,interference_when_not_treated,observations_less_likely_reveal,share_with_friends_family,bring_up_physical_interview,bring_up_physical_why,bring_up_mental_interview,bring_up_mental_why,openly_identified,identified_affected_career,identified_affected_how,team_reaction_if_knew,observed_unsupportive_response,unsupportive_response_desc,observed_supportive_response,supportive_response_desc,industry_support_rating,improvement_suggestions,additional_comments,willing_to_interview,age,gender,country_live,state_live,race,country_work,state_work
323,2014,2014,No,More than 1000,Yes,NaN,Yes,Yes,No,Yes,Yes,Don't know,Don't know,No,Maybe,Some of them,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,Sometimes,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,2014,2014,No,100-500,Yes,NaN,Don't know,No,No,Don't know,Don't know,Don't know,No,No,Maybe,Some of them,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,Yes,Sometimes,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2842,2020,2020,NaN,100-500,1.0,1.0,Not eligible for coverage / NA,No,No,No,I don't know,Difficult,Physical health,No,1.0,Maybe,1.0,1.0,7.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,"No, none did",N/A (none offered),None did,None did,I don't know,Physical health,Some of my previous supervisors,0.0,At some of my previous employers,1.0,7.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,1,Yes,NaN,NaN,No,8.0,Yes,NaN,NaN,I would bring up physical health issues if the...,1,1.0,2.0,NaN,NaN,I was promoted from engineer to engineering ma...,NaN,NaN,2.0,"Everyone is unique, and many of us have slight...",Thank you,NaN,32.0,Male,NaN,NaN,NaN,NaN,NaN
2625,2019,2019,NaN,More than 1000,False,True,I don't know,No,No,No,I don't know,Very easy,Physical health,Maybe,False,Maybe,False,True,7.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,I don't know,N/A (was not aware),None did,None did,I don't know,Physical health,"No, none of my previous supervisors",False,"No, at none of my previous employers",False,6.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Possibly,True,Yes,NaN,NaN,No,7.0,Yes,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,28.0,Male,NaN,NaN,NaN,NaN,NaN
2390,2018,2018,NaN,More than 1000,0.0,1.0,Yes,Yes,Yes,Yes,Yes,I don't know,Physical health,No,0.0,No,0.0,1.0,9.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,Some did,I was aware of some,None did,Some did,I don't know,Physical health,"No, none of my previous supervisors",0.0,At some of my previous employers,0.0,7.0,5.0,Possibly,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Possibly,0,Yes,Not applicable to me,Sometimes,No,3.0,No,NaN,No,It's not applicable to the type of job that I'...,0,NaN,NaN,5.0,Maybe/Not sure,NaN,Maybe/Not sure,NaN,3.0,NaN,NaN,0.0,41.0,Male,United States of America,Minnesota,White,United States of America,Minnesota
1830,2017,2017,NaN,26-100,1.0,1.0,NaN,Yes,No,No,Yes,Very easy,Same level of comfort for each,Yes,1.0,Yes,1.0,1.0,3.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Possibly,1,No,Rarely,Often,No,10.0,Maybe,NaN,Yes,I would only bring it up if would affect my work.,1.0,0.0,NaN,NaN,Maybe/Not sure,NaN,"Yes, I observed",NaN,2.0,When someone is suffereing from a mental illne...,NaN,NaN,44.0,Male,United States of America,Alabama,White,United States of America,Alabama
15,2014,2014,NaN,26-100,Yes,NaN,Yes,Not sure,No,No,Don't know,Somewhat easy,Don't know,Some of them,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,Rarely,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2207,2018,2018,NaN,More than 1000,1.0,1.0,Yes,Yes,I don't know,I don't know,Yes,Neither easy nor difficult,Physical health,Yes,1.0,Maybe,1.0,0.0,8.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,"Yes, they all did","Yes, I was aware of all of them",None did,None did,Sometimes,Physical health,Some of my previous supervisors,1.0,At some of my previous employers,1.0,7.0,3.0,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,1,Yes,Sometimes,Often,NaN,7.0,No,NaN,No,not a good idea,0,NaN,NaN,2.0,"Yes, I experienced","my boss tried to use it against me, hoping to ...","Yes, I experienced",NaN,2.0,NaN,NaN,1.0,37.0,f,United States of America,Indiana,White,United States of America,Indiana
2748,2019,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,"Yes, I know several","No, because it would impact me negatively","No, because it would impact me negatively",Yes,51-75%,NaN,False,I don't know,N/A (was not aware),I don't know,None did,I don't know,Physical health,"No, none of my previous supervisors",False,"No, at none of my previous employers",False,8.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,True,Yes,NaN,NaN,Yes,10.0,No,NaN,NaN,it may be seen as a potential unwanted burden ...,False,NaN,NaN,NaN,NaN,bipolar disorder often gets blamed for mercuri...,NaN,NaN,3.0,employee mental health needs to become part of...,EEOO surveys include bipolar disorder as a dis...,NaN,36.0,female,NaN,NaN,Black or African American,NaN,NaN
2674,2019,2019,NaN,500-1000,True,True,No,No,No,No,I don't know,Somewhat easy,Same level of comfort for each,No,False,Maybe,False,False,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,I don't know,N/A (was not aware),I don't know,Some did,I don't know,Physical health,"No, none of my previous supervisors",False,"No, at none of my previous employers",False,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,False,No,NaN,NaN,NaN,3.0,No,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,28.0,male,NaN,NaN,NaN,NaN,NaN

## Dataset Dimensions

Understanding the size of the dataset helps estimate its complexity and computational requirements.

In [8]:
rows, cols = df.shape

print(f"Number of Rows : {rows:,}")
print(f"Number of Columns : {cols}")

Number of Rows : 3,095
Number of Columns : 85

## Dataset Information

This section provides information about:

- Data types
- Missing values
- Memory usage
- Total non-null observations

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 85 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   source_file                        3095 non-null   int64
 1   survey_year                        3095 non-null   int64
 2   self_employed                      1241 non-null   str
 3   no_employees                       2836 non-null   str
 4   tech_company                       2836 non-null   str
 5   primary_role_tech                  1577 non-null   str
 6   benefits                           2193 non-null   str
 7   know_options                       2673 non-null   str
 8   formal_discussion                  2836 non-null   str
 9   resources                          2836 non-null   str
 10  anonymity                          2836 non-null   str
 11  leave_ease                         2836 non-null   str
 12  comfort_physical_mental            2836 non-null   str
 13  comfort_supervisor                 2836 non-null   str
 14  discussed_with_employer            2836 non-null   str
 15  comfort_coworkers                  2836 non-null   str
 16  discussed_with_coworkers           1572 non-null   str
 17  coworker_discussed_with_you        1569 non-null   str
 18  employer_importance_physical       1577 non-null   float64
 19  employer_importance_mental         1577 non-null   float64
 20  coverage_mental_health             259 non-null    str
 21  know_resources                     259 non-null    str
 22  reveal_to_clients                  259 non-null    str
 23  reveal_to_coworkers                259 non-null    str
 24  productivity_affected              259 non-null    str
 25  productivity_percent_affected      194 non-null    str
 26  have_prev_employers                1173 non-null   float64
 27  prev_tech_company                  1546 non-null   str
 28  prev_benefits                      1546 non-null   str
 29  prev_know_options                  1546 non-null   str
 30  prev_formal_discussion             1546 non-null   str
 31  prev_resources                     1546 non-null   str
 32  prev_anonymity                     1546 non-null   str
 33  prev_comfort_physical_mental       1546 non-null   str
 34  prev_comfort_supervisor            1546 non-null   str
 35  prev_discussed_with_employer       1546 non-null   str
 36  prev_comfort_coworkers             1546 non-null   str
 37  prev_discussed_with_coworkers      1538 non-null   str
 38  prev_employer_importance_physical  1546 non-null   float64
 39  prev_employer_importance_mental    1546 non-null   float64
 40  currently_disordered               1173 non-null   str
 41  diagnosed_disorder                 515 non-null    str
 42  disorder_anxiety                   0 non-null      float64
 43  disorder_mood                      0 non-null      float64
 44  disorder_psychotic                 0 non-null      float64
 45  disorder_eating                    0 non-null      float64
 46  disorder_adh_add                   0 non-null      float64
 47  disorder_personality               0 non-null      float64
 48  disorder_ocd                       0 non-null      float64
 49  disorder_ptsd                      0 non-null      float64
 50  disorder_stress_response           0 non-null      float64
 51  disorder_dissociative              0 non-null      float64
 52  disorder_substance_use             0 non-null      float64
 53  disorder_addictive                 0 non-null      float64
 54  disorder_other                     0 non-null      float64
 55  past_disorder                      1813 non-null   str
 56  sought_treatment                   3095 non-null   str
 57  family_history                     3095 non-null   str
 58  interference_when_treated          2168 non-null   str
 59  interference_when_not_treated      1173 non-null   str
 60  observations_less_likely_reveal    2707 non-null   str
 61  share_with_friends_family          1836 non-null   float64
 62  bring_up_physical_interview        1836 non-null   str
 63  bring_up_physical_why              0 non-null      float64
 64  bring_up_mental_interview          1173 non-null   str
 65  bring_up_mental_why                1410 non-null   str
 66  openly_identified                  1834 non-null   str
 67  identified_affected_career         222 non-null    str
 68  identified_affected_how            82 non-null     float64
 69  team_reaction_if_knew              417 non-null    float64
 70  observed_unsupportive_response     1171 non-null   str
 71  unsupportive_response_desc         405 non-null    str
 72  observed_supportive_response       1171 non-null   str
 73  supportive_response_desc           0 non-null      float64
 74  industry_support_rating            1834 non-null   float64
 75  improvement_suggestions            1268 non-null   str
 76  additional_comments                493 non-null    str
 77  willing_to_interview               417 non-null    float64
 78  age                                1834 non-null   float64
 79  gender                             1808 non-null   str
 80  country_live                       1171 non-null   str
 81  state_live                         808 non-null    str
 82  race                               1101 non-null   str
 83  country_work                       1171 non-null   str
 84  state_work                         817 non-null    str
dtypes: float64(26), int64(2), str(57)
memory usage: 2.0 MB

## Statistical Summary

A statistical overview of all numerical variables including:

- Mean
- Median
- Standard Deviation
- Quartiles
- Minimum
- Maximum

In [11]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
source_file,3095.0,2016.485622,2.277820,2014.0,2014.0,2017.0,2018.00,2021.0
survey_year,3095.0,2016.485622,2.277820,2014.0,2014.0,2017.0,2018.00,2021.0
employer_importance_physical,1577.0,6.317058,2.279832,0.0,5.0,7.0,8.00,10.0
employer_importance_mental,1577.0,5.027901,2.500859,0.0,3.0,5.0,7.00,10.0
have_prev_employers,1173.0,0.878090,0.327321,0.0,1.0,1.0,1.00,1.0
prev_employer_importance_physical,1546.0,5.413325,2.603817,0.0,4.0,5.0,7.00,10.0
prev_employer_importance_mental,1546.0,3.518111,2.534422,0.0,1.0,3.0,5.00,10.0
disorder_anxiety,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
disorder_mood,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
disorder_psychotic,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
disorder_eating,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
disorder_adh_add,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
disorder_personality,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
disorder_ocd,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
disorder_ptsd,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
disorder_stress_response,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
disorder_dissociative,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
disorder_substance_use,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
disorder_addictive,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
disorder_other,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
share_with_friends_family,1836.0,6.404139,2.747714,0.0,5.0,7.0,8.25,10.0
bring_up_physical_why,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
identified_affected_how,82.0,3.902439,2.502393,0.0,2.0,3.0,5.75,10.0
team_reaction_if_knew,417.0,5.354916,2.296251,0.0,4.0,5.0,7.00,10.0
supportive_response_desc,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
industry_support_rating,1834.0,2.572519,0.953031,1.0,2.0,3.0,3.00,5.0
willing_to_interview,417.0,0.366906,0.482540,0.0,0.0,0.0,1.00,1.0
age,1834.0,34.811341,9.723979,0.0,28.0,34.0,40.00,223.0

## Summary of Categorical Variables

Explore all categorical features.

In [13]:
df.describe(include="object").T

,count,unique,top,freq
self_employed,1241,2,No,1095
no_employees,2836,6,More than 1000,776
tech_company,2836,6,Yes,1031
primary_role_tech,1577,4,1.0,1181
benefits,2193,5,Yes,972
know_options,2673,3,No,1259
formal_discussion,2836,4,No,1789
resources,2836,4,No,1318
anonymity,2836,4,I don't know,948
leave_ease,2836,8,Somewhat easy,691
comfort_physical_mental,2836,6,Physical health,1070
comfort_supervisor,2836,4,Yes,1097
discussed_with_employer,2836,7,0.0,883
comfort_coworkers,2836,4,Some of them,774
discussed_with_coworkers,1572,4,0.0,722
coworker_discussed_with_you,1569,4,0.0,663
coverage_mental_health,259,4,1.0,142
know_resources,259,3,I know some,93
reveal_to_clients,259,5,Not applicable to me,79
reveal_to_coworkers,259,5,Not applicable to me,84
productivity_affected,259,4,Yes,194
productivity_percent_affected,194,4,1-25%,83
prev_tech_company,1546,4,1.0,848
prev_benefits,1546,4,Some did,524
prev_know_options,1546,5,I was aware of some,491
prev_formal_discussion,1546,4,None did,1038
prev_resources,1546,3,None did,1007
prev_anonymity,1546,4,I don't know,1010
prev_comfort_physical_mental,1546,3,Physical health,1154
prev_comfort_supervisor,1546,4,Some of my previous supervisors,740
prev_discussed_with_employer,1546,4,0.0,973
prev_comfort_coworkers,1546,4,At some of my previous employers,761
prev_discussed_with_coworkers,1538,4,0.0,810
currently_disordered,1173,4,Yes,515
diagnosed_disorder,515,2,Yes,503
past_disorder,1813,4,Yes,782
sought_treatment,3095,6,1,865
family_history,3095,3,No,1359
interference_when_treated,2168,5,Sometimes,792
interference_when_not_treated,1173,5,Often,496
observations_less_likely_reveal,2707,3,No,1924
bring_up_physical_interview,1836,3,Maybe,755
bring_up_mental_interview,1173,3,No,821
bring_up_mental_why,1410,1385,\n,6
openly_identified,1834,6,0.0,668
identified_affected_career,222,4,0.0,113
observed_unsupportive_response,1171,5,No,501
unsupportive_response_desc,405,403,.,2
observed_supportive_response,1171,5,No,415
improvement_suggestions,1268,1241,\n,5
additional_comments,493,365,No,36
gender,1808,119,Male,747
country_live,1171,56,United States of America,809
state_live,808,43,Illinois,126
race,1101,10,White,956
country_work,1171,58,United States of America,817
state_work,817,44,Illinois,127

## Missing Value Analysis

Missing values are one of the most common challenges in real-world datasets.

Understanding the percentage of missing values helps determine the appropriate preprocessing strategy.

In [15]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum()/len(df))*100
})

missing = missing.sort_values("Percentage", ascending=False)

missing

                                   Missing Values  Percentage
disorder_ptsd                                3095  100.000000
disorder_ocd                                 3095  100.000000
disorder_personality                         3095  100.000000
disorder_adh_add                             3095  100.000000
disorder_eating                              3095  100.000000
disorder_dissociative                        3095  100.000000
disorder_other                               3095  100.000000
bring_up_physical_why                        3095  100.000000
supportive_response_desc                     3095  100.000000
disorder_addictive                           3095  100.000000
disorder_mood                                3095  100.000000
disorder_anxiety                             3095  100.000000
disorder_psychotic                           3095  100.000000
disorder_substance_use                       3095  100.000000
disorder_stress_response                     3095  100.000000
identified_affected_how                      3013   97.350565
productivity_percent_affected                2901   93.731826
identified_affected_career                   2873   92.827141
productivity_affected                        2836   91.631664
know_resources                               2836   91.631664
coverage_mental_health                       2836   91.631664
reveal_to_coworkers                          2836   91.631664
reveal_to_clients                            2836   91.631664
unsupportive_response_desc                   2690   86.914378
team_reaction_if_knew                        2678   86.526656
willing_to_interview                         2678   86.526656
additional_comments                          2602   84.071082
diagnosed_disorder                           2580   83.360258
state_live                                   2287   73.893376
state_work                                   2278   73.602585
race                                         1994   64.426494
observed_unsupportive_response               1924   62.164782
country_work                                 1924   62.164782
observed_supportive_response                 1924   62.164782
country_live                                 1924   62.164782
interference_when_not_treated                1922   62.100162
bring_up_mental_interview                    1922   62.100162
currently_disordered                         1922   62.100162
have_prev_employers                          1922   62.100162
self_employed                                1854   59.903069
improvement_suggestions                      1827   59.030695
bring_up_mental_why                          1685   54.442649
prev_discussed_with_coworkers                1557   50.306947
prev_resources                               1549   50.048465
prev_employer_importance_physical            1549   50.048465
prev_employer_importance_mental              1549   50.048465
prev_formal_discussion                       1549   50.048465
prev_discussed_with_employer                 1549   50.048465
prev_comfort_coworkers                       1549   50.048465
prev_know_options                            1549   50.048465
prev_comfort_supervisor                      1549   50.048465
prev_tech_company                            1549   50.048465
prev_benefits                                1549   50.048465
prev_comfort_physical_mental                 1549   50.048465
prev_anonymity                               1549   50.048465
coworker_discussed_with_you                  1526   49.305331
discussed_with_coworkers                     1523   49.208401
primary_role_tech                            1518   49.046850
employer_importance_physical                 1518   49.046850
employer_importance_mental                   1518   49.046850
gender                                       1287   41.583199
past_disorder                                1282   41.421648
age                                          1261   40.743134
industry_support_rating                      1261   40.743134
openly_identified                            1261   40.743134
bring_up_physical_interview                  1259   40.678514
share_with_friends_family                    1259   40.678514
interference_when_treated                     927   29.951535
benefits                                      902   29.143780
know_options                                  422   13.634895
observations_less_likely_reveal               388   12.536349
discussed_with_employer                       259    8.368336
comfort_supervisor                            259    8.368336
tech_company                                  259    8.368336
no_employees                                  259    8.368336
comfort_coworkers                             259    8.368336
formal_discussion                             259    8.368336
resources                                     259    8.368336
anonymity                                     259    8.368336
leave_ease                                    259    8.368336
comfort_physical_mental                       259    8.368336
source_file                                     0    0.000000
survey_year                                     0    0.000000
sought_treatment                                0    0.000000
family_history                                  0    0.000000

In [16]:
missing[missing["Missing Values"] > 0]

                                   Missing Values  Percentage
disorder_ptsd                                3095  100.000000
disorder_ocd                                 3095  100.000000
disorder_personality                         3095  100.000000
disorder_adh_add                             3095  100.000000
disorder_eating                              3095  100.000000
disorder_dissociative                        3095  100.000000
disorder_other                               3095  100.000000
bring_up_physical_why                        3095  100.000000
supportive_response_desc                     3095  100.000000
disorder_addictive                           3095  100.000000
disorder_mood                                3095  100.000000
disorder_anxiety                             3095  100.000000
disorder_psychotic                           3095  100.000000
disorder_substance_use                       3095  100.000000
disorder_stress_response                     3095  100.000000
identified_affected_how                      3013   97.350565
productivity_percent_affected                2901   93.731826
identified_affected_career                   2873   92.827141
productivity_affected                        2836   91.631664
know_resources                               2836   91.631664
coverage_mental_health                       2836   91.631664
reveal_to_coworkers                          2836   91.631664
reveal_to_clients                            2836   91.631664
unsupportive_response_desc                   2690   86.914378
team_reaction_if_knew                        2678   86.526656
willing_to_interview                         2678   86.526656
additional_comments                          2602   84.071082
diagnosed_disorder                           2580   83.360258
state_live                                   2287   73.893376
state_work                                   2278   73.602585
race                                         1994   64.426494
observed_unsupportive_response               1924   62.164782
country_work                                 1924   62.164782
observed_supportive_response                 1924   62.164782
country_live                                 1924   62.164782
interference_when_not_treated                1922   62.100162
bring_up_mental_interview                    1922   62.100162
currently_disordered                         1922   62.100162
have_prev_employers                          1922   62.100162
self_employed                                1854   59.903069
improvement_suggestions                      1827   59.030695
bring_up_mental_why                          1685   54.442649
prev_discussed_with_coworkers                1557   50.306947
prev_resources                               1549   50.048465
prev_employer_importance_physical            1549   50.048465
prev_employer_importance_mental              1549   50.048465
prev_formal_discussion                       1549   50.048465
prev_discussed_with_employer                 1549   50.048465
prev_comfort_coworkers                       1549   50.048465
prev_know_options                            1549   50.048465
prev_comfort_supervisor                      1549   50.048465
prev_tech_company                            1549   50.048465
prev_benefits                                1549   50.048465
prev_comfort_physical_mental                 1549   50.048465
prev_anonymity                               1549   50.048465
coworker_discussed_with_you                  1526   49.305331
discussed_with_coworkers                     1523   49.208401
primary_role_tech                            1518   49.046850
employer_importance_physical                 1518   49.046850
employer_importance_mental                   1518   49.046850
gender                                       1287   41.583199
past_disorder                                1282   41.421648
age                                          1261   40.743134
industry_support_rating                      1261   40.743134
openly_identified                            1261   40.743134
bring_up_physical_interview                  1259   40.678514
share_with_friends_family                    1259   40.678514
interference_when_treated                     927   29.951535
benefits                                      902   29.143780
know_options                                  422   13.634895
observations_less_likely_reveal               388   12.536349
discussed_with_employer                       259    8.368336
comfort_supervisor                            259    8.368336
tech_company                                  259    8.368336
no_employees                                  259    8.368336
comfort_coworkers                             259    8.368336
formal_discussion                             259    8.368336
resources                                     259    8.368336
anonymity                                     259    8.368336
leave_ease                                    259    8.368336
comfort_physical_mental                       259    8.368336

## Duplicate Record Analysis

Duplicate records can introduce bias into the analysis and machine learning models.

This section identifies duplicate observations.

In [18]:
duplicates = df.duplicated().sum()

print(f"Duplicate Rows : {duplicates}")

Duplicate Rows : 13

## Feature Data Types

Understanding the distribution of feature types assists in selecting suitable preprocessing and visualization techniques.

In [19]:
dtype_summary = df.dtypes.value_counts()

dtype_summary

str        57
float64    26
int64       2
Name: count, dtype: int64

## Unique Values per Feature

The number of unique values indicates whether a feature is:

- Binary
- Categorical
- High-cardinality
- Continuous

In [21]:
unique = pd.DataFrame({
    "Unique Values": df.nunique()
})

unique.sort_values("Unique Values")

                                   Unique Values
disorder_ocd                                   0
disorder_ptsd                                  0
disorder_stress_response                       0
disorder_dissociative                          0
disorder_substance_use                         0
disorder_addictive                             0
disorder_other                                 0
bring_up_physical_why                          0
disorder_adh_add                               0
disorder_personality                           0
disorder_mood                                  0
disorder_anxiety                               0
disorder_eating                                0
disorder_psychotic                             0
supportive_response_desc                       0
self_employed                                  2
diagnosed_disorder                             2
have_prev_employers                            2
willing_to_interview                           2
prev_comfort_physical_mental                   3
prev_resources                                 3
bring_up_physical_interview                    3
know_resources                                 3
know_options                                   3
family_history                                 3
bring_up_mental_interview                      3
observations_less_likely_reveal                3
coworker_discussed_with_you                    4
discussed_with_coworkers                       4
coverage_mental_health                         4
productivity_percent_affected                  4
productivity_affected                          4
formal_discussion                              4
resources                                      4
anonymity                                      4
prev_anonymity                                 4
prev_comfort_coworkers                         4
prev_discussed_with_coworkers                  4
prev_comfort_supervisor                        4
prev_discussed_with_employer                   4
currently_disordered                           4
past_disorder                                  4
prev_benefits                                  4
prev_tech_company                              4
prev_formal_discussion                         4
comfort_supervisor                             4
primary_role_tech                              4
comfort_coworkers                              4
identified_affected_career                     4
benefits                                       5
interference_when_not_treated                  5
observed_supportive_response                   5
interference_when_treated                      5
reveal_to_clients                              5
prev_know_options                              5
reveal_to_coworkers                            5
industry_support_rating                        5
observed_unsupportive_response                 5
sought_treatment                               6
source_file                                    6
tech_company                                   6
comfort_physical_mental                        6
survey_year                                    6
no_employees                                   6
openly_identified                              6
discussed_with_employer                        7
leave_ease                                     8
identified_affected_how                       10
race                                          10
employer_importance_physical                  11
prev_employer_importance_mental               11
employer_importance_mental                    11
share_with_friends_family                     11
prev_employer_importance_physical             11
team_reaction_if_knew                         11
state_live                                    43
state_work                                    44
age                                           55
country_live                                  56
country_work                                  58
gender                                       119
additional_comments                          365
unsupportive_response_desc                   403
improvement_suggestions                     1241
bring_up_mental_why                         1385

## Data Dictionary

This table provides a concise description of each feature within the unified dataset.

It serves as a reference throughout the project.

In [23]:
dictionary = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values,
    "Missing Values": df.isnull().sum().values,
    "Unique Values": df.nunique().values
})

dictionary

                               Column Data Type  Missing Values  Unique Values
0                         source_file     int64               0              6
1                         survey_year     int64               0              6
2                       self_employed       str            1854              2
3                        no_employees       str             259              6
4                        tech_company       str             259              6
5                   primary_role_tech       str            1518              4
6                            benefits       str             902              5
7                        know_options       str             422              3
8                   formal_discussion       str             259              4
9                           resources       str             259              4
10                          anonymity       str             259              4
11                         leave_ease       str             259              8
12            comfort_physical_mental       str             259              6
13                 comfort_supervisor       str             259              4
14            discussed_with_employer       str             259              7
15                  comfort_coworkers       str             259              4
16           discussed_with_coworkers       str            1523              4
17        coworker_discussed_with_you       str            1526              4
18       employer_importance_physical   float64            1518             11
19         employer_importance_mental   float64            1518             11
20             coverage_mental_health       str            2836              4
21                     know_resources       str            2836              3
22                  reveal_to_clients       str            2836              5
23                reveal_to_coworkers       str            2836              5
24              productivity_affected       str            2836              4
25      productivity_percent_affected       str            2901              4
26                have_prev_employers   float64            1922              2
27                  prev_tech_company       str            1549              4
28                      prev_benefits       str            1549              4
29                  prev_know_options       str            1549              5
30             prev_formal_discussion       str            1549              4
31                     prev_resources       str            1549              3
32                     prev_anonymity       str            1549              4
33       prev_comfort_physical_mental       str            1549              3
34            prev_comfort_supervisor       str            1549              4
35       prev_discussed_with_employer       str            1549              4
36             prev_comfort_coworkers       str            1549              4
37      prev_discussed_with_coworkers       str            1557              4
38  prev_employer_importance_physical   float64            1549             11
39    prev_employer_importance_mental   float64            1549             11
40               currently_disordered       str            1922              4
41                 diagnosed_disorder       str            2580              2
42                   disorder_anxiety   float64            3095              0
43                      disorder_mood   float64            3095              0
44                 disorder_psychotic   float64            3095              0
45                    disorder_eating   float64            3095              0
46                   disorder_adh_add   float64            3095              0
47               disorder_personality   float64            3095              0
48                       disorder_ocd   float64            3095              0
49                      disorder_ptsd   float64            3095              0
50           disorder_stress_response   float64            3095              0
51              disorder_dissociative   float64            3095              0
52             disorder_substance_use   float64            3095              0
53                 disorder_addictive   float64            3095              0
54                     disorder_other   float64            3095              0
55                      past_disorder       str            1282              4
56                   sought_treatment       str               0              6
57                     family_history       str               0              3
58          interference_when_treated       str             927              5
59      interference_when_not_treated       str            1922              5
60    observations_less_likely_reveal       str             388              3
61          share_with_friends_family   float64            1259             11
62        bring_up_physical_interview       str            1259              3
63              bring_up_physical_why   float64            3095              0
64          bring_up_mental_interview       str            1922              3
65                bring_up_mental_why       str            1685           1385
66                  openly_identified       str            1261              6
67         identified_affected_career       str            2873              4
68            identified_affected_how   float64            3013             10
69              team_reaction_if_knew   float64            2678             11
70     observed_unsupportive_response       str            1924              5
71         unsupportive_response_desc       str            2690            403
72       observed_supportive_response       str            1924              5
73           supportive_response_desc   float64            3095              0
74            industry_support_rating   float64            1261              5
75            improvement_suggestions       str            1827           1241
76                additional_comments       str            2602            365
77               willing_to_interview   float64            2678              2
78                                age   float64            1261             55
79                             gender       str            1287            119
80                       country_live       str            1924             56
81                         state_live       str            2287             43
82                               race       str            1994             10
83                       country_work       str            1924             58
84                         state_work       str            2278             44

## Dataset Memory Usage

Evaluating memory consumption helps optimize data processing pipelines, especially for larger datasets.