# 🧠 Mental Health Intelligence Platform

## Phase 3 : Data Harmonizing

### Objective

The objective of this notebook is to standardize categorical variables across all OSMI survey years after data cleaning.

Although duplicate records, missing values, and invalid observations have already been addressed, survey responses collected across different years still contain inconsistencies such as:

- Different spellings
- Different capitalization
- Abbreviations
- Multiple representations of the same response
- Survey-specific response options

The harmonization process ensures that equivalent responses share a common representation while preserving the original meaning of the data.

The resulting dataset will be used for Exploratory Data Analysis (EDA), Feature Engineering, and Machine Learning.

In [3]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

df = pd.read_csv("../data/processed/cleaned_osmi_data.csv")

print(df.shape)

df.head()

(3082, 70)

,source_file,survey_year,self_employed,no_employees,tech_company,primary_role_tech,benefits,know_options,formal_discussion,resources,anonymity,leave_ease,comfort_physical_mental,comfort_supervisor,discussed_with_employer,comfort_coworkers,discussed_with_coworkers,coworker_discussed_with_you,employer_importance_physical,employer_importance_mental,coverage_mental_health,know_resources,reveal_to_clients,reveal_to_coworkers,productivity_affected,productivity_percent_affected,have_prev_employers,prev_tech_company,prev_benefits,prev_know_options,prev_formal_discussion,prev_resources,prev_anonymity,prev_comfort_physical_mental,prev_comfort_supervisor,prev_discussed_with_employer,prev_comfort_coworkers,prev_discussed_with_coworkers,prev_employer_importance_physical,prev_employer_importance_mental,currently_disordered,diagnosed_disorder,past_disorder,sought_treatment,family_history,interference_when_treated,interference_when_not_treated,observations_less_likely_reveal,share_with_friends_family,bring_up_physical_interview,bring_up_mental_interview,bring_up_mental_why,openly_identified,identified_affected_career,identified_affected_how,team_reaction_if_knew,observed_unsupportive_response,unsupportive_response_desc,observed_supportive_response,industry_support_rating,improvement_suggestions,additional_comments,willing_to_interview,age,gender,country_live,state_live,race,country_work,state_work
0,2014,2014,NaN,6-25,Yes,NaN,Yes,Not sure,No,Yes,Yes,Somewhat easy,Yes,Yes,No,Some of them,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,No,Often,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2014,2014,NaN,More than 1000,No,NaN,Don't know,No,Don't know,Don't know,Don't know,Don't know,Don't know,No,Maybe,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,Rarely,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014,2014,NaN,6-25,Yes,NaN,No,No,No,No,Don't know,Somewhat difficult,No,Yes,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,Rarely,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2014,2014,NaN,26-100,Yes,NaN,No,Yes,No,No,No,Somewhat difficult,No,No,Yes,Some of them,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,Often,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014,2014,NaN,100-500,Yes,NaN,Yes,No,Don't know,Don't know,Don't know,Don't know,Don't know,Yes,No,Some of them,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,Never,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Inspect Survey Years

Since this dataset combines multiple OSMI surveys, we first identify the survey years present in the data.

This helps us understand which records belong to each survey and allows year-specific harmonization where necessary.

In [5]:
df["source_file"].value_counts().sort_index()

source_file
2014    1246
2017     756
2018     417
2019     352
2020     180
2021     131
Name: count, dtype: int64

## Inspect Categorical Variables by Survey Year

Different survey years often use different response formats for the same question.

Inspecting each categorical variable separately for every survey year helps identify inconsistencies before harmonization.

In [6]:
categorical = df.select_dtypes(include="object").columns

years = sorted(df["source_file"].dropna().unique())

for year in years:

    print("\n")
    print("="*100)
    print(f"SURVEY YEAR : {year}")
    print("="*100)

    subset = df[df["source_file"] == year]

    for col in categorical:

        print("\n")
        print(col)
        print("-"*40)

        display(subset[col].value_counts(dropna=False))

====================================================================================================
SURVEY YEAR : 2014
====================================================================================================


self_employed
----------------------------------------

C:\Users\Acelin Nazareth\AppData\Local\Temp\ipykernel_28056\789457241.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical = df.select_dtypes(include="object").columns

self_employed
No     1086
Yes     142
NaN      18
Name: count, dtype: int64

no_employees
----------------------------------------

no_employees
6-25              286
26-100            286
More than 1000    280
100-500           176
1-5               158
500-1000           60
Name: count, dtype: int64

tech_company
----------------------------------------

tech_company
Yes    1019
No      227
Name: count, dtype: int64

primary_role_tech
----------------------------------------

primary_role_tech
NaN    1246
Name: count, dtype: int64

benefits
----------------------------------------

benefits
Yes           475
Don't know    405
No            366
Name: count, dtype: int64

know_options
----------------------------------------

know_options
No          498
Yes         438
Not sure    310
Name: count, dtype: int64

formal_discussion
----------------------------------------

formal_discussion
No            833
Yes           226
Don't know    187
Name: count, dtype: int64

resources
----------------------------------------

resources
No            638
Don't know    361
Yes           247
Name: count, dtype: int64

anonymity
----------------------------------------

anonymity
Don't know    812
Yes           372
No             62
Name: count, dtype: int64

leave_ease
----------------------------------------

leave_ease
Don't know            558
Somewhat easy         263
Very easy             203
Somewhat difficult    125
Very difficult         97
Name: count, dtype: int64

comfort_physical_mental
----------------------------------------

comfort_physical_mental
Don't know    570
Yes           339
No            337
Name: count, dtype: int64

comfort_supervisor
----------------------------------------

comfort_supervisor
Yes             509
No              389
Some of them    348
Name: count, dtype: int64

discussed_with_employer
----------------------------------------

discussed_with_employer
No       483
Maybe    475
Yes      288
Name: count, dtype: int64

comfort_coworkers
----------------------------------------

comfort_coworkers
Some of them    767
No              257
Yes             222
Name: count, dtype: int64

discussed_with_coworkers
----------------------------------------

discussed_with_coworkers
NaN    1246
Name: count, dtype: int64

coworker_discussed_with_you
----------------------------------------

coworker_discussed_with_you
NaN    1246
Name: count, dtype: int64

coverage_mental_health
----------------------------------------

coverage_mental_health
NaN    1246
Name: count, dtype: int64

know_resources
----------------------------------------

know_resources
NaN    1246
Name: count, dtype: int64

reveal_to_clients
----------------------------------------

reveal_to_clients
NaN    1246
Name: count, dtype: int64

reveal_to_coworkers
----------------------------------------

reveal_to_coworkers
NaN    1246
Name: count, dtype: int64

productivity_affected
----------------------------------------

productivity_affected
NaN    1246
Name: count, dtype: int64

productivity_percent_affected
----------------------------------------

productivity_percent_affected
NaN    1246
Name: count, dtype: int64

prev_tech_company
----------------------------------------

prev_tech_company
NaN    1246
Name: count, dtype: int64

prev_benefits
----------------------------------------

prev_benefits
NaN    1246
Name: count, dtype: int64

prev_know_options
----------------------------------------

prev_know_options
NaN    1246
Name: count, dtype: int64

prev_formal_discussion
----------------------------------------

prev_formal_discussion
NaN    1246
Name: count, dtype: int64

prev_resources
----------------------------------------

prev_resources
NaN    1246
Name: count, dtype: int64

prev_anonymity
----------------------------------------

prev_anonymity
NaN    1246
Name: count, dtype: int64

prev_comfort_physical_mental
----------------------------------------

prev_comfort_physical_mental
NaN    1246
Name: count, dtype: int64

prev_comfort_supervisor
----------------------------------------

prev_comfort_supervisor
NaN    1246
Name: count, dtype: int64

prev_discussed_with_employer
----------------------------------------

prev_discussed_with_employer
NaN    1246
Name: count, dtype: int64

prev_comfort_coworkers
----------------------------------------

prev_comfort_coworkers
NaN    1246
Name: count, dtype: int64

prev_discussed_with_coworkers
----------------------------------------

prev_discussed_with_coworkers
NaN    1246
Name: count, dtype: int64

currently_disordered
----------------------------------------

currently_disordered
NaN    1246
Name: count, dtype: int64

diagnosed_disorder
----------------------------------------

diagnosed_disorder
NaN    1246
Name: count, dtype: int64

past_disorder
----------------------------------------

past_disorder
NaN    1246
Name: count, dtype: int64

sought_treatment
----------------------------------------

sought_treatment
Yes    632
No     614
Name: count, dtype: int64

family_history
----------------------------------------

family_history
No     759
Yes    487
Name: count, dtype: int64

interference_when_treated
----------------------------------------

interference_when_treated
Sometimes    464
NaN          257
Never        213
Rarely       171
Often        141
Name: count, dtype: int64

interference_when_not_treated
----------------------------------------

interference_when_not_treated
NaN    1246
Name: count, dtype: int64

observations_less_likely_reveal
----------------------------------------

observations_less_likely_reveal
No     1065
Yes     181
Name: count, dtype: int64

bring_up_physical_interview
----------------------------------------

bring_up_physical_interview
NaN    1246
Name: count, dtype: int64

bring_up_mental_interview
----------------------------------------

bring_up_mental_interview
NaN    1246
Name: count, dtype: int64

bring_up_mental_why
----------------------------------------

bring_up_mental_why
NaN    1246
Name: count, dtype: int64

openly_identified
----------------------------------------

openly_identified
NaN    1246
Name: count, dtype: int64

identified_affected_career
----------------------------------------

identified_affected_career
NaN    1246
Name: count, dtype: int64

observed_unsupportive_response
----------------------------------------

observed_unsupportive_response
NaN    1246
Name: count, dtype: int64

unsupportive_response_desc
----------------------------------------

unsupportive_response_desc
NaN    1246
Name: count, dtype: int64

observed_supportive_response
----------------------------------------

observed_supportive_response
NaN    1246
Name: count, dtype: int64

improvement_suggestions
----------------------------------------

improvement_suggestions
NaN    1246
Name: count, dtype: int64

additional_comments
----------------------------------------

additional_comments
NaN    1246
Name: count, dtype: int64

gender
----------------------------------------

gender
NaN    1246
Name: count, dtype: int64

country_live
----------------------------------------

country_live
NaN    1246
Name: count, dtype: int64

state_live
----------------------------------------

state_live
NaN    1246
Name: count, dtype: int64

race
----------------------------------------

race
NaN    1246
Name: count, dtype: int64

country_work
----------------------------------------

country_work
NaN    1246
Name: count, dtype: int64

state_work
----------------------------------------

state_work
NaN    1246
Name: count, dtype: int64

====================================================================================================
SURVEY YEAR : 2017
====================================================================================================


self_employed
----------------------------------------

self_employed
NaN    756
Name: count, dtype: int64

no_employees
----------------------------------------

no_employees
100-500           203
More than 1000    158
26-100            128
NaN               113
6-25               86
500-1000           48
1-5                20
Name: count, dtype: int64

tech_company
----------------------------------------

tech_company
1.0    501
0.0    142
NaN    113
Name: count, dtype: int64

primary_role_tech
----------------------------------------

primary_role_tech
1.0    595
NaN    113
0.0     48
Name: count, dtype: int64

benefits
----------------------------------------

benefits
NaN    756
Name: count, dtype: int64

know_options
----------------------------------------

know_options
No     308
Yes    268
NaN    180
Name: count, dtype: int64

formal_discussion
----------------------------------------

formal_discussion
No              409
Yes             162
NaN             113
I don't know     72
Name: count, dtype: int64

resources
----------------------------------------

resources
No              279
Yes             188
I don't know    176
NaN             113
Name: count, dtype: int64

anonymity
----------------------------------------

anonymity
I don't know    395
Yes             215
NaN             113
No               33
Name: count, dtype: int64

leave_ease
----------------------------------------

leave_ease
Somewhat easy                 164
Very easy                     144
NaN                           113
I don't know                  105
Neither easy nor difficult    102
Somewhat difficult             71
Difficult                      57
Name: count, dtype: int64

comfort_physical_mental
----------------------------------------

comfort_physical_mental
Physical health                   435
Same level of comfort for each    198
NaN                               113
Mental health                      10
Name: count, dtype: int64

comfort_supervisor
----------------------------------------

comfort_supervisor
Yes      256
Maybe    221
No       166
NaN      113
Name: count, dtype: int64

discussed_with_employer
----------------------------------------

discussed_with_employer
0.0    437
1.0    206
NaN    113
Name: count, dtype: int64

comfort_coworkers
----------------------------------------

comfort_coworkers
Maybe    285
Yes      206
No       152
NaN      113
Name: count, dtype: int64

discussed_with_coworkers
----------------------------------------

discussed_with_coworkers
0.0    353
1.0    290
NaN    113
Name: count, dtype: int64

coworker_discussed_with_you
----------------------------------------

coworker_discussed_with_you
0.0    325
1.0    313
NaN    118
Name: count, dtype: int64

coverage_mental_health
----------------------------------------

coverage_mental_health
NaN    643
1.0     79
0.0     34
Name: count, dtype: int64

know_resources
----------------------------------------

know_resources
NaN                     643
Yes, I know several      39
I know some              39
No, I don't know any     35
Name: count, dtype: int64

reveal_to_clients
----------------------------------------

reveal_to_clients
NaN                                          643
Not applicable to me                          38
No, because it would impact me negatively     30
Sometimes, if it comes up                     29
No, because it doesn't matter                 14
Yes, always                                    2
Name: count, dtype: int64

reveal_to_coworkers
----------------------------------------

reveal_to_coworkers
NaN                                          643
Sometimes, if it comes up                     44
Not applicable to me                          36
No, because it would impact me negatively     22
No, because it doesn't matter                  6
Yes, always                                    5
Name: count, dtype: int64

productivity_affected
----------------------------------------

productivity_affected
NaN                     643
Yes                      85
Unsure                   13
Not applicable to me      8
No                        7
Name: count, dtype: int64

productivity_percent_affected
----------------------------------------

productivity_percent_affected
NaN        671
1-25%       38
26-50%      29
51-75%      12
76-100%      6
Name: count, dtype: int64

prev_tech_company
----------------------------------------

prev_tech_company
1.0    456
0.0    211
NaN     89
Name: count, dtype: int64

prev_benefits
----------------------------------------

prev_benefits
Some did             231
No, none did         161
I don't know         151
Yes, they all did    124
NaN                   89
Name: count, dtype: int64

prev_know_options
----------------------------------------

prev_know_options
I was aware of some                228
N/A (was not aware)                200
N/A (none offered)                 107
NaN                                 89
Yes, I was aware of all of them     87
No, I only became aware later       45
Name: count, dtype: int64

prev_formal_discussion
----------------------------------------

prev_formal_discussion
None did             461
Some did             151
NaN                   89
I don't know          40
Yes, they all did     15
Name: count, dtype: int64

prev_resources
----------------------------------------

prev_resources
None did             448
Some did             187
NaN                   89
Yes, they all did     32
Name: count, dtype: int64

prev_anonymity
----------------------------------------

prev_anonymity
I don't know    447
Yes, always     120
NaN              89
Sometimes        54
No               46
Name: count, dtype: int64

prev_comfort_physical_mental
----------------------------------------

prev_comfort_physical_mental
Physical health                   515
Same level of comfort for each    145
NaN                                89
Mental health                       7
Name: count, dtype: int64

prev_comfort_supervisor
----------------------------------------

prev_comfort_supervisor
Some of my previous supervisors        327
No, none of my previous supervisors    249
NaN                                     89
Yes, all of my previous supervisors     50
I don't know                            41
Name: count, dtype: int64

prev_discussed_with_employer
----------------------------------------

prev_discussed_with_employer
0.0    525
1.0    142
NaN     89
Name: count, dtype: int64

prev_comfort_coworkers
----------------------------------------

prev_comfort_coworkers
At some of my previous employers        301
No, at none of my previous employers    244
NaN                                      89
Some of my previous employers            81
Yes, at all of my previous employers     41
Name: count, dtype: int64

prev_discussed_with_coworkers
----------------------------------------

prev_discussed_with_coworkers
0.0    447
1.0    219
NaN     90
Name: count, dtype: int64

currently_disordered
----------------------------------------

currently_disordered
Yes           324
No            222
Possibly      144
Don't Know     66
Name: count, dtype: int64

diagnosed_disorder
----------------------------------------

diagnosed_disorder
NaN    432
Yes    314
No      10
Name: count, dtype: int64

past_disorder
----------------------------------------

past_disorder
Yes           332
No            227
Possibly      134
Don't Know     53
NaN            10
Name: count, dtype: int64

sought_treatment
----------------------------------------

sought_treatment
1    456
0    300
Name: count, dtype: int64

family_history
----------------------------------------

family_history
Yes             339
No              224
I don't know    193
Name: count, dtype: int64

interference_when_treated
----------------------------------------

interference_when_treated
Not applicable to me    279
Sometimes               222
Rarely                  191
Often                    43
Never                    21
Name: count, dtype: int64

interference_when_not_treated
----------------------------------------

interference_when_not_treated
Often                   310
Not applicable to me    251
Sometimes               157
Rarely                   31
Never                     7
Name: count, dtype: int64

observations_less_likely_reveal
----------------------------------------

observations_less_likely_reveal
No       361
NaN      160
Maybe    127
Yes      108
Name: count, dtype: int64

bring_up_physical_interview
----------------------------------------

bring_up_physical_interview
Maybe    303
No       278
Yes      175
Name: count, dtype: int64

bring_up_mental_interview
----------------------------------------

bring_up_mental_interview
No       524
Maybe    194
Yes       38
Name: count, dtype: int64

bring_up_mental_why
----------------------------------------

bring_up_mental_why
NaN                                                                      189
Fear of not getting the job                                                3
Fear of discrimination                                                     2
None of their business.                                                    2
Privacy                                                                    2
                                                                        ...
Depends how relevant it is                                                 1
Full disclosure, work accommodations.                                      1
ww                                                                         1
because none of the phyiscal things wrong with me dont affect my work      1
Lala                                                                       1
Name: count, Length: 563, dtype: int64

openly_identified
----------------------------------------

openly_identified
0.0    668
1.0     86
NaN      2
Name: count, dtype: int64

identified_affected_career
----------------------------------------

identified_affected_career
NaN    672
0.0     58
1.0     26
Name: count, dtype: int64

observed_unsupportive_response
----------------------------------------

observed_unsupportive_response
No                                323
Maybe/Not sure                    210
Yes, I observed                   128
Yes, I experienced                 86
I've always been self-employed      7
NaN                                 2
Name: count, dtype: int64

unsupportive_response_desc
----------------------------------------

unsupportive_response_desc
NaN                                                                                                                                                                                                                                     599
During a discussion about "mental health first aider" at work, a coworker dismissed the whole idea, saying that "no one here suffers from Mental Health Disorder"                                                                         1
I was suffering depression and I was open about that, that is why my numbers fell, but then I started drinking too much and admitted myself into a detox/psych facility to get better... 5 days later I get out to find myself fired      1
ok                                                                                                                                                                                                                                        1
Was told it does not matter.                                                                                                                                                                                                              1
                                                                                                                                                                                                                                       ...
Mocking people for suffering from ptsd, disbelief of symptoms, telling people to "get over it"                                                                                                                                            1
A supervisor of another team spoke of a former coworker (at another company) who may have had a mental health issue and said supervisor was very disparaging about the incident and the coworker.                                         1
Mocking, criticism, and complaints about that person                                                                                                                                                                                      1
I've seen coworkers dismissive of mental health disorders, claiming people were "making them up to get out of doing their job".                                                                                                           1
Co worker had depression and needed time off. Was let go.                                                                                                                                                                                 1
Name: count, Length: 158, dtype: int64

observed_supportive_response
----------------------------------------

observed_supportive_response
No                                260
Maybe/Not sure                    199
Yes, I observed                   147
Yes, I experienced                140
I've always been self-employed      8
NaN                                 2
Name: count, dtype: int64

improvement_suggestions
----------------------------------------

improvement_suggestions
NaN                                                                                                                                                                                                                                                        258
Not sure                                                                                                                                                                                                                                                     2
Empathy                                                                                                                                                                                                                                                      2
dont know                                                                                                                                                                                                                                                    2
?                                                                                                                                                                                                                                                            2
                                                                                                                                                                                                                                                          ...
Stop focusing on Rockstars and making it impossible to take time off                                                                                                                                                                                         1
Be more educated that mental health issues are common and do not make a person less capable of being productive contributors to the company's success. Be flexible and understanding when employees need accommodations to maintain good mental health.      1
Encourage mental health first aid training in additional to physical first aid                                                                                                                                                                               1
Openness, resources, concessions, flexibility when mental health issues affect work.                                                                                                                                                                         1
openness could be better.                                                                                                                                                                                                                                    1
Name: count, Length: 492, dtype: int64

additional_comments
----------------------------------------

additional_comments
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                               583
No                                                                                                                                                                                                                                                                                                                                                                                                                                                                 17
no                                                                                                                                                                                                                                                                                                                                                                                                                                                                 13
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                   4
nope                                                                                                                                                                                                                                                                                                                                                                                                                                                                3
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ...
I'd be curious in the future if there are some mental health issues that are perceived as MORE acceptable than others--I feel fine saying I have an anxiety disorder, but I never talk about my PTSD. I also know a developer who never discusses their borderline personality disorder bc of stigmas attached to it.                                                                                                                                               1
In my previous job, getting questioned for the reason for taking personal days was a big thing. As well as the ability to work from home. I think these things are really important, especially for those working in tech jobs, to feel that they are trusted by their employer and that they are supported by their employer. I think it comes down to healthy and effective communication, check ins and removing ambiguity around what is or isn't allowed.      1
Thanks                                                                                                                                                                                                                                                                                                                                                                                                                                                              1
Mental health is an important topic, but it gets ignored for the most part. Something needs to be done but I don't know how to get there                                                                                                                                                                                                                                                                                                                            1
Man of the survey questions mentioned "mental health disorder" even though I said I've never been diagnosed, which means I can't technically answer about "mental health disorders." Many of my answers would be related to "mental health issues."                                                                                                                                                                                                                 1
Name: count, Length: 136, dtype: int64

gender
----------------------------------------

gender
Male                                                         334
Female                                                       111
male                                                         102
female                                                        63
M                                                             27
m                                                             23
F                                                             16
NaN                                                           14
f                                                             13
Nonbinary                                                      4
Woman                                                          4
Man                                                            3
Cis-male                                                       2
woman                                                          2
Genderfluid                                                    1
cis-male                                                       1
Mail                                                           1
male/androgynous                                               1
cis hetero male                                                1
femalw                                                         1
femail                                                         1
Male (cis)                                                     1
uhhhhhhhhh fem genderqueer?                                    1
male (hey this is the tech industry you're talking about)      1
female (cis)                                                   1
God King of the Valajar                                        1
Cis male                                                       1
man                                                            1
My sex is female.                                              1
Non-binary                                                     1
Male, cis                                                      1
cis male                                                       1
Agender/genderfluid                                            1
Male-ish                                                       1
sometimes                                                      1
female (cisgender)                                             1
Female (cis)                                                   1
Woman-identified                                               1
Contextual                                                     1
Non binary                                                     1
Genderqueer demigirl                                           1
Genderqueer/non-binary                                         1
cis-Female                                                     1
cis female                                                     1
nonbinary                                                      1
F, cisgender                                                   1
Female-ish                                                     1
\-                                                             1
trans woman                                                    1
Transfeminine                                                  1
Cis Male                                                       1
dude                                                           1
Name: count, dtype: int64

country_live
----------------------------------------

country_live
United States of America    497
United Kingdom               66
Canada                       26
Germany                      22
France                       17
Spain                        15
Netherlands                  14
India                        13
Australia                    12
Switzerland                   6
Romania                       4
New Zealand                   4
Ireland                       4
Russia                        3
Japan                         3
Belgium                       3
South Africa                  3
Sweden                        3
Argentina                     3
Mexico                        3
Indonesia                     2
Portugal                      2
Czech Republic                2
Pakistan                      2
Hungary                       2
Bulgaria                      2
Greece                        2
Brazil                        2
Ukraine                       2
NaN                           2
Bangladesh                    1
Israel                        1
Iceland                       1
Finland                       1
Serbia                        1
Jordan                        1
Croatia                       1
Italy                         1
Poland                        1
Singapore                     1
Slovakia                      1
Austria                       1
Belarus                       1
Turkey                        1
Latvia                        1
Name: count, dtype: int64

state_live
----------------------------------------

state_live
NaN                     259
Illinois                 76
California               60
Ohio                     39
Indiana                  35
Washington               26
Tennessee                20
Minnesota                19
Oregon                   17
Michigan                 17
Nebraska                 17
New York                 16
Texas                    15
Massachusetts            15
Georgia                  13
Maryland                 12
Missouri                 11
Pennsylvania              9
Virginia                  9
Utah                      8
Colorado                  6
Wisconsin                 6
North Carolina            6
New Jersey                6
Iowa                      5
Arizona                   4
Alabama                   4
Kentucky                  3
Florida                   3
Louisiana                 2
Kansas                    2
New Mexico                2
Idaho                     2
Nevada                    2
New Hampshire             2
Montana                   1
District of Columbia      1
Alaska                    1
North Dakota              1
South Dakota              1
South Carolina            1
Maine                     1
Connecticut               1
Name: count, dtype: int64

race
----------------------------------------

race
White                         435
NaN                           274
More than one of the above     14
I prefer not to answer         14
Asian                          13
Black or African American       6
Name: count, dtype: int64

country_work
----------------------------------------

country_work
United States of America    503
United Kingdom               66
Canada                       26
Germany                      22
France                       16
Spain                        15
Netherlands                  14
India                        12
Australia                    12
Switzerland                   5
Romania                       4
New Zealand                   4
Russia                        3
Japan                         3
Portugal                      3
South Africa                  3
Sweden                        3
Mexico                        3
Ireland                       3
Indonesia                     2
Pakistan                      2
Bulgaria                      2
Argentina                     2
Austria                       2
Ukraine                       2
Belgium                       2
NaN                           2
Bangladesh                    1
Israel                        1
Iceland                       1
Finland                       1
Serbia                        1
Jordan                        1
Hungary                       1
Croatia                       1
Italy                         1
Eritrea                       1
Greece                        1
Swaziland                     1
Brazil                        1
Poland                        1
Singapore                     1
Slovakia                      1
Luxembourg                    1
Turkey                        1
Czech Republic                1
Latvia                        1
Name: count, dtype: int64

state_work
----------------------------------------

state_work
NaN                     253
Illinois                 76
California               67
Ohio                     38
Indiana                  34
Washington               26
New York                 23
Tennessee                19
Minnesota                19
Massachusetts            17
Michigan                 17
Nebraska                 17
Oregon                   15
Texas                    14
Georgia                  10
Missouri                  9
Pennsylvania              9
Virginia                  9
Maryland                  9
Utah                      7
Colorado                  6
Wisconsin                 6
North Carolina            6
Iowa                      6
Arizona                   5
Kentucky                  4
District of Columbia      4
Alabama                   4
Kansas                    3
New Jersey                3
Florida                   3
New Mexico                2
Idaho                     2
Nevada                    2
New Hampshire             2
Connecticut               2
Montana                   1
Alaska                    1
North Dakota              1
South Dakota              1
South Carolina            1
Mississippi               1
Maine                     1
Louisiana                 1
Name: count, dtype: int64

====================================================================================================
SURVEY YEAR : 2018
====================================================================================================


self_employed
----------------------------------------

self_employed
NaN    417
Name: count, dtype: int64

no_employees
----------------------------------------

no_employees
More than 1000    105
100-500            81
26-100             70
6-25               69
NaN                56
500-1000           31
1-5                 5
Name: count, dtype: int64

tech_company
----------------------------------------

tech_company
1.0    266
0.0     95
NaN     56
Name: count, dtype: int64

primary_role_tech
----------------------------------------

primary_role_tech
1.0    346
NaN     56
0.0     15
Name: count, dtype: int64

benefits
----------------------------------------

benefits
Yes                               213
I don't know                       85
NaN                                56
No                                 42
Not eligible for coverage / NA     21
Name: count, dtype: int64

know_options
----------------------------------------

know_options
Yes    164
No     160
NaN     93
Name: count, dtype: int64

formal_discussion
----------------------------------------

formal_discussion
No              228
Yes             103
NaN              56
I don't know     30
Name: count, dtype: int64

resources
----------------------------------------

resources
No              144
Yes             117
I don't know    100
NaN              56
Name: count, dtype: int64

anonymity
----------------------------------------

anonymity
I don't know    221
Yes             124
NaN              56
No               16
Name: count, dtype: int64

leave_ease
----------------------------------------

leave_ease
Somewhat easy                 109
I don't know                   72
Very easy                      72
NaN                            56
Somewhat difficult             39
Difficult                      36
Neither easy nor difficult     33
Name: count, dtype: int64

comfort_physical_mental
----------------------------------------

comfort_physical_mental
Physical health                   240
Same level of comfort for each    114
NaN                                56
Mental health                       7
Name: count, dtype: int64

comfort_supervisor
----------------------------------------

comfort_supervisor
Yes      131
Maybe    117
No       113
NaN       56
Name: count, dtype: int64

discussed_with_employer
----------------------------------------

discussed_with_employer
0.0    245
1.0    116
NaN     56
Name: count, dtype: int64

comfort_coworkers
----------------------------------------

comfort_coworkers
Maybe    161
Yes      112
No        88
NaN       56
Name: count, dtype: int64

discussed_with_coworkers
----------------------------------------

discussed_with_coworkers
0.0    213
1.0    147
NaN     57
Name: count, dtype: int64

coworker_discussed_with_you
----------------------------------------

coworker_discussed_with_you
0.0    187
1.0    173
NaN     57
Name: count, dtype: int64

coverage_mental_health
----------------------------------------

coverage_mental_health
NaN    361
1.0     41
0.0     15
Name: count, dtype: int64

know_resources
----------------------------------------

know_resources
NaN                     361
I know some              24
Yes, I know several      18
No, I don't know any     14
Name: count, dtype: int64

reveal_to_clients
----------------------------------------

reveal_to_clients
NaN                                          361
Not applicable to me                          19
No, because it would impact me negatively     18
Sometimes, if it comes up                      9
No, because it doesn't matter                  9
Yes, always                                    1
Name: count, dtype: int64

reveal_to_coworkers
----------------------------------------

reveal_to_coworkers
NaN                                          361
Sometimes, if it comes up                     19
Not applicable to me                          18
No, because it would impact me negatively     12
No, because it doesn't matter                  4
Yes, always                                    3
Name: count, dtype: int64

productivity_affected
----------------------------------------

productivity_affected
NaN                     361
Yes                      41
Not applicable to me      8
No                        4
Unsure                    3
Name: count, dtype: int64

productivity_percent_affected
----------------------------------------

productivity_percent_affected
NaN        376
1-25%       18
26-50%      13
51-75%       9
76-100%      1
Name: count, dtype: int64

prev_tech_company
----------------------------------------

prev_tech_company
1.0    257
0.0    106
NaN     54
Name: count, dtype: int64

prev_benefits
----------------------------------------

prev_benefits
Some did             138
No, none did          89
I don't know          77
Yes, they all did     59
NaN                   54
Name: count, dtype: int64

prev_know_options
----------------------------------------

prev_know_options
I was aware of some                122
N/A (was not aware)                 98
N/A (none offered)                  64
NaN                                 54
Yes, I was aware of all of them     53
No, I only became aware later       26
Name: count, dtype: int64

prev_formal_discussion
----------------------------------------

prev_formal_discussion
None did             249
Some did              80
NaN                   54
I don't know          21
Yes, they all did     13
Name: count, dtype: int64

prev_resources
----------------------------------------

prev_resources
None did             239
Some did              98
NaN                   54
Yes, they all did     26
Name: count, dtype: int64

prev_anonymity
----------------------------------------

prev_anonymity
I don't know    234
Yes, always      71
NaN              54
No               35
Sometimes        23
Name: count, dtype: int64

prev_comfort_physical_mental
----------------------------------------

prev_comfort_physical_mental
Physical health                   254
Same level of comfort for each    107
NaN                                54
Mental health                       2
Name: count, dtype: int64

prev_comfort_supervisor
----------------------------------------

prev_comfort_supervisor
Some of my previous supervisors        183
No, none of my previous supervisors    122
NaN                                     54
Yes, all of my previous supervisors     30
I don't know                            28
Name: count, dtype: int64

prev_discussed_with_employer
----------------------------------------

prev_discussed_with_employer
0.0    280
1.0     83
NaN     54
Name: count, dtype: int64

prev_comfort_coworkers
----------------------------------------

prev_comfort_coworkers
At some of my previous employers        207
No, at none of my previous employers    123
NaN                                      54
Yes, at all of my previous employers     33
Name: count, dtype: int64

prev_discussed_with_coworkers
----------------------------------------

prev_discussed_with_coworkers
0.0    227
1.0    135
NaN     55
Name: count, dtype: int64

currently_disordered
----------------------------------------

currently_disordered
Yes           191
No            112
Possibly       82
Don't Know     32
Name: count, dtype: int64

diagnosed_disorder
----------------------------------------

diagnosed_disorder
NaN    226
Yes    189
No       2
Name: count, dtype: int64

past_disorder
----------------------------------------

past_disorder
Yes           203
No            111
Possibly       69
Don't Know     32
NaN             2
Name: count, dtype: int64

sought_treatment
----------------------------------------

sought_treatment
1    263
0    154
Name: count, dtype: int64

family_history
----------------------------------------

family_history
Yes             208
No              114
I don't know     95
Name: count, dtype: int64

interference_when_treated
----------------------------------------

interference_when_treated
Not applicable to me    153
Rarely                  112
Sometimes               105
Often                    32
Never                    15
Name: count, dtype: int64

interference_when_not_treated
----------------------------------------

interference_when_not_treated
Often                   186
Not applicable to me    134
Sometimes                79
Rarely                   17
Never                     1
Name: count, dtype: int64

observations_less_likely_reveal
----------------------------------------

observations_less_likely_reveal
No       200
NaN       97
Yes       63
Maybe     57
Name: count, dtype: int64

bring_up_physical_interview
----------------------------------------

bring_up_physical_interview
Maybe    177
No       161
Yes       79
Name: count, dtype: int64

bring_up_mental_interview
----------------------------------------

bring_up_mental_interview
No       297
Maybe    100
Yes       20
Name: count, dtype: int64

bring_up_mental_why
----------------------------------------

bring_up_mental_why
NaN                                                                                                                                93
None of their business                                                                                                              2
Discrimination                                                                                                                      2
Fear of discrimination                                                                                                              2
no                                                                                                                                  2
                                                                                                                                   ..
I am visually impaired.                                                                                                             1
Embarrassing                                                                                                                        1
If it mattered to the job, I'd bring it up immediately, to see how they react and best judge if it's some place I'd want to be.     1
Could interfere with job                                                                                                            1
It isn't the place to do so unless it directly impacts my ability to do the job                                                     1
Name: count, Length: 320, dtype: int64

openly_identified
----------------------------------------

openly_identified
0    366
1     51
Name: count, dtype: int64

identified_affected_career
----------------------------------------

identified_affected_career
NaN    366
0.0     35
1.0     16
Name: count, dtype: int64

observed_unsupportive_response
----------------------------------------

observed_unsupportive_response
No                                178
Maybe/Not sure                    102
Yes, I observed                    82
Yes, I experienced                 50
I've always been self-employed      5
Name: count, dtype: int64

unsupportive_response_desc
----------------------------------------

unsupportive_response_desc
NaN                                                                                                                                                                                                                                                                                                                                          327
I saw people who were on “stress” leave ridiculed, or talked about as thought they were it feeling the truth, or just wanted time off                                                                                                                                                                                                          1
Criticism                                                                                                                                                                                                                                                                                                                                      1
A past employer was upset I was disorganized and forgetting things. I explained my ADHD and that I need help. I was told it was 100% up to me to manage my work.                                                                                                                                                                               1
There is not really any sort of support for mental health issues at my place of employment. There is a phone number you can call if you want to talk to a third party help line and that is about it. I see people here that are clearly suffering but the prevalent attitude is that you should just suck it up and keep plodding along.      1
                                                                                                                                                                                                                                                                                                                                            ...
Someone said they had been diagnosed with anxiety or deoression. One person said we've all been there. Another started viewing that employee differently and didn't trust them to be capable of handling hard tasks. It affected their raise at the end if the year.                                                                           1
In a badly managed and supported team I was told that as I'm so influencing, I need to watch my "mood" because it runs off on the team                                                                                                                                                                                                         1
Actionable workplace abuse                                                                                                                                                                                                                                                                                                                     1
Blaming the victim. Reducing responsibilities in a way that reduces respect and influence.                                                                                                                                                                                                                                                     1
Coworker transitioned mtf and was treated poorly by coworkers and management                                                                                                                                                                                                                                                                   1
Name: count, Length: 91, dtype: int64

observed_supportive_response
----------------------------------------

observed_supportive_response
No                                155
Maybe/Not sure                     96
Yes, I experienced                 84
Yes, I observed                    79
I've always been self-employed      3
Name: count, dtype: int64

improvement_suggestions
----------------------------------------

improvement_suggestions
NaN                                                                                                                                                                                                                                                                                                          129
no                                                                                                                                                                                                                                                                                                             2
Since the industry is male dominated, there should be more talk to increase awareness and reduce stigma. Offering peer support programs and role models would also help make the discussion ok                                                                                                                 1
it's a comfort thing at this point imo, needs to be talked about so it doesn't feel weird to bring up issues                                                                                                                                                                                                   1
If it is mentioned at all, it's during a meeting to go over benefits. The same was true with welness programs at all of my employers. It could be greatly improved by socializing the availability of benefits and resources throughout the year--especially around holidays when lots of folks struggle.      1
                                                                                                                                                                                                                                                                                                            ...
The tech industry needs to understand that mental health is as important as physical health and that mental health and physical health affect people all over the industry                                                                                                                                     1
Acknowledge its existence                                                                                                                                                                                                                                                                                      1
Be more open, understand how to respond to people opening up about mental health issues, and how to react to people having an episode. Accept that mental health is just like physical health.                                                                                                                 1
Provide training or resources to educate or normalize health differences                                                                                                                                                                                                                                       1
Be more welcoming and supportive. Accept mental health as a non taboo subject and simply a part of life.                                                                                                                                                                                                       1
Name: count, Length: 288, dtype: int64

additional_comments
----------------------------------------

additional_comments
NaN                                                                                                                                                                                                                                                                                                               324
No                                                                                                                                                                                                                                                                                                                  6
no                                                                                                                                                                                                                                                                                                                  4
.                                                                                                                                                                                                                                                                                                                   2
I thinka lot of people "grin and bear it". I've followed what OSMH has been doing with interest because it seems so obvious and so right. It also occurs to me that the stigma will take a generation to work through. It's going to be a long road to get from starting a conversation at work to acceptance.      1
                                                                                                                                                                                                                                                                                                                 ...
Interesting matter                                                                                                                                                                                                                                                                                                  1
Companies optimize for their own benefit. These problems won’t be solved unless they company benefits financially.                                                                                                                                                                                                  1
mo                                                                                                                                                                                                                                                                                                                  1
We have lots of tech user groups across many disciplines, but a meetup for mental health that everyone could attend would be awesome.                                                                                                                                                                               1
Thanks                                                                                                                                                                                                                                                                                                              1
Name: count, Length: 85, dtype: int64

gender
----------------------------------------

gender
Male                             168
Female                            78
male                              58
female                            20
M                                 17
m                                 12
F                                  7
f                                  7
NaN                                4
Woman                              3
cis male                           3
woman                              2
Man                                2
Genderqueer                        2
Ostensibly Male                    1
Agender                            1
male, born with xy chromosoms      1
Malel                              1
MALE                               1
I identify as female               1
*shrug emoji* (F)                  1
Nonbinary                          1
Male (or female, or both)          1
Trans man                          1
Cis-male                           1
transgender                        1
non binary                         1
Female/gender non-binary.          1
Cis woman                          1
Cis Male                           1
Female (cisgender)                 1
Cis-Female                         1
Cisgendered woman                  1
Trans woman                        1
genderfluid                        1
Demiguy                            1
Trans female                       1
Cisgender male                     1
non-binary                         1
She/her/they/them                  1
Other                              1
Cis female                         1
SWM                                1
cisgender female                   1
NB                                 1
Genderfluid                        1
Nonbinary/femme                    1
gender non-conforming woman        1
Name: count, dtype: int64

country_live
----------------------------------------

country_live
United States of America    312
United Kingdom               19
Canada                        8
Germany                       7
Poland                        6
India                         5
Netherlands                   5
Australia                     4
Italy                         4
France                        4
Norway                        3
Ireland                       3
Spain                         3
Finland                       2
Serbia                        2
Colombia                      2
Brazil                        2
Japan                         2
Mexico                        2
Russia                        1
Ukraine                       1
Estonia                       1
South Africa                  1
Mauritius                     1
Saudi Arabia                  1
Nigeria                       1
Kenya                         1
Uruguay                       1
Bangladesh                    1
New Zealand                   1
Belgium                       1
Switzerland                   1
Portugal                      1
Ethiopia                      1
Macedonia                     1
Iceland                       1
Greece                        1
Hong Kong                     1
Georgia                       1
Turkey                        1
Austria                       1
Name: count, dtype: int64

state_live
----------------------------------------

state_live
NaN                     106
Illinois                 50
California               34
Pennsylvania             19
Tennessee                16
Washington               16
Massachusetts            14
Minnesota                14
Michigan                 14
Texas                    13
New York                 13
Nebraska                 12
Florida                  10
Oregon                   10
Wisconsin                 9
Ohio                      8
Missouri                  6
Indiana                   6
New Jersey                6
New Hampshire             5
Georgia                   5
Iowa                      3
North Carolina            3
Kansas                    3
Colorado                  3
South Carolina            2
Connecticut               2
Rhode Island              2
Kentucky                  2
North Dakota              2
Alabama                   1
Maryland                  1
Idaho                     1
Nevada                    1
New Mexico                1
Virginia                  1
Utah                      1
Arizona                   1
District of Columbia      1
Name: count, dtype: int64

race
----------------------------------------

race
White                               265
NaN                                 115
More than one of the above           13
I prefer not to answer                9
Asian                                 9
Black or African American             5
American Indian or Alaska Native      1
Name: count, dtype: int64

country_work
----------------------------------------

country_work
United States of America    314
United Kingdom               20
Canada                        8
Germany                       6
Poland                        5
India                         5
Netherlands                   5
Australia                     4
Italy                         4
Norway                        3
Ireland                       3
Spain                         3
France                        3
Mexico                        3
Finland                       2
Serbia                        2
Colombia                      2
Brazil                        2
Switzerland                   2
Russia                        1
Ukraine                       1
Estonia                       1
South Africa                  1
Mauritius                     1
Saudi Arabia                  1
Nigeria                       1
Kenya                         1
Uruguay                       1
Bangladesh                    1
Japan                         1
New Zealand                   1
Portugal                      1
Ethiopia                      1
Macedonia                     1
Iceland                       1
Greece                        1
Hong Kong                     1
Georgia                       1
Turkey                        1
Austria                       1
Name: count, dtype: int64

state_work
----------------------------------------

state_work
NaN                     103
Illinois                 51
California               41
Pennsylvania             19
Massachusetts            15
Tennessee                15
Washington               14
Minnesota                14
New York                 14
Texas                    13
Michigan                 13
Florida                  11
Nebraska                 11
Oregon                    9
Wisconsin                 8
New Jersey                8
Ohio                      8
Missouri                  6
Georgia                   5
Indiana                   5
Colorado                  4
Iowa                      3
New Hampshire             3
North Carolina            3
South Carolina            2
Connecticut               2
Rhode Island              2
Kansas                    2
Kentucky                  2
North Dakota              2
District of Columbia      2
Alabama                   1
Maryland                  1
Idaho                     1
Nevada                    1
Virginia                  1
Utah                      1
Arizona                   1
Name: count, dtype: int64

====================================================================================================
SURVEY YEAR : 2019
====================================================================================================


self_employed
----------------------------------------

self_employed
NaN    352
Name: count, dtype: int64

no_employees
----------------------------------------

no_employees
More than 1000    111
100-500            80
NaN                48
26-100             45
6-25               34
500-1000           27
1-5                 7
Name: count, dtype: int64

tech_company
----------------------------------------

tech_company
True     207
False     97
NaN       48
Name: count, dtype: int64

primary_role_tech
----------------------------------------

primary_role_tech
True     282
NaN       48
False     22
Name: count, dtype: int64

benefits
----------------------------------------

benefits
Yes                               164
I don't know                       87
NaN                                48
No                                 35
Not eligible for coverage / NA     18
Name: count, dtype: int64

know_options
----------------------------------------

know_options
No     148
Yes    130
NaN     74
Name: count, dtype: int64

formal_discussion
----------------------------------------

formal_discussion
No              176
Yes             104
NaN              48
I don't know     24
Name: count, dtype: int64

resources
----------------------------------------

resources
No              130
Yes             102
I don't know     72
NaN              48
Name: count, dtype: int64

anonymity
----------------------------------------

anonymity
I don't know    188
Yes             101
NaN              48
No               15
Name: count, dtype: int64

leave_ease
----------------------------------------

leave_ease
Somewhat easy                 83
Very easy                     70
I don't know                  52
Somewhat difficult            49
NaN                           48
Neither easy nor difficult    31
Difficult                     19
Name: count, dtype: int64

comfort_physical_mental
----------------------------------------

comfort_physical_mental
Physical health                   209
Same level of comfort for each     93
NaN                                48
Mental health                       2
Name: count, dtype: int64

comfort_supervisor
----------------------------------------

comfort_supervisor
Yes      117
Maybe     95
No        92
NaN       48
Name: count, dtype: int64

discussed_with_employer
----------------------------------------

discussed_with_employer
False    204
True     100
NaN       48
Name: count, dtype: int64

comfort_coworkers
----------------------------------------

comfort_coworkers
Maybe    128
Yes       89
No        87
NaN       48
Name: count, dtype: int64

discussed_with_coworkers
----------------------------------------

discussed_with_coworkers
False    157
True     144
NaN       51
Name: count, dtype: int64

coworker_discussed_with_you
----------------------------------------

coworker_discussed_with_you
False    162
True     142
NaN       48
Name: count, dtype: int64

coverage_mental_health
----------------------------------------

coverage_mental_health
NaN      304
True      32
False     16
Name: count, dtype: int64

know_resources
----------------------------------------

know_resources
NaN                     304
No, I don't know any     18
I know some              17
Yes, I know several      13
Name: count, dtype: int64

reveal_to_clients
----------------------------------------

reveal_to_clients
NaN                                          304
Not applicable to me                          17
Sometimes, if it comes up                     14
No, because it would impact me negatively      9
No, because it doesn't matter                  6
Yes, always                                    2
Name: count, dtype: int64

reveal_to_coworkers
----------------------------------------

reveal_to_coworkers
NaN                                          304
Not applicable to me                          21
Sometimes, if it comes up                     17
No, because it doesn't matter                  5
No, because it would impact me negatively      3
Yes, always                                    2
Name: count, dtype: int64

productivity_affected
----------------------------------------

productivity_affected
NaN                     304
Yes                      37
Unsure                    6
Not applicable to me      4
No                        1
Name: count, dtype: int64

productivity_percent_affected
----------------------------------------

productivity_percent_affected
NaN        315
1-25%       16
26-50%      11
51-75%       6
76-100%      4
Name: count, dtype: int64

prev_tech_company
----------------------------------------

prev_tech_company
True     188
False    108
NaN       56
Name: count, dtype: int64

prev_benefits
----------------------------------------

prev_benefits
Some did             92
I don't know         78
No, none did         78
NaN                  56
Yes, they all did    48
Name: count, dtype: int64

prev_know_options
----------------------------------------

prev_know_options
N/A (was not aware)                95
I was aware of some                82
N/A (none offered)                 60
NaN                                56
Yes, I was aware of all of them    30
No, I only became aware later      29
Name: count, dtype: int64

prev_formal_discussion
----------------------------------------

prev_formal_discussion
None did             194
Some did              73
NaN                   56
I don't know          25
Yes, they all did      4
Name: count, dtype: int64

prev_resources
----------------------------------------

prev_resources
None did             185
Some did              98
NaN                   56
Yes, they all did     13
Name: count, dtype: int64

prev_anonymity
----------------------------------------

prev_anonymity
I don't know    204
NaN              56
Yes, always      46
Sometimes        24
No               22
Name: count, dtype: int64

prev_comfort_physical_mental
----------------------------------------

prev_comfort_physical_mental
Physical health                   218
Same level of comfort for each     72
NaN                                56
Mental health                       6
Name: count, dtype: int64

prev_comfort_supervisor
----------------------------------------

prev_comfort_supervisor
Some of my previous supervisors        144
No, none of my previous supervisors    114
NaN                                     56
I don't know                            20
Yes, all of my previous supervisors     18
Name: count, dtype: int64

prev_discussed_with_employer
----------------------------------------

prev_discussed_with_employer
False    220
True      76
NaN       56
Name: count, dtype: int64

prev_comfort_coworkers
----------------------------------------

prev_comfort_coworkers
At some of my previous employers        158
No, at none of my previous employers    111
NaN                                      56
Yes, at all of my previous employers     27
Name: count, dtype: int64

prev_discussed_with_coworkers
----------------------------------------

prev_discussed_with_coworkers
False    180
True     114
NaN       58
Name: count, dtype: int64

currently_disordered
----------------------------------------

currently_disordered
NaN    352
Name: count, dtype: int64

diagnosed_disorder
----------------------------------------

diagnosed_disorder
NaN    352
Name: count, dtype: int64

past_disorder
----------------------------------------

past_disorder
Yes           146
No            107
Possibly       72
Don't Know     24
NaN             3
Name: count, dtype: int64

sought_treatment
----------------------------------------

sought_treatment
True     217
False    135
Name: count, dtype: int64

family_history
----------------------------------------

family_history
Yes             159
No              107
I don't know     86
Name: count, dtype: int64

interference_when_treated
----------------------------------------

interference_when_treated
NaN    352
Name: count, dtype: int64

interference_when_not_treated
----------------------------------------

interference_when_not_treated
NaN    352
Name: count, dtype: int64

observations_less_likely_reveal
----------------------------------------

observations_less_likely_reveal
No       173
NaN       70
Yes       65
Maybe     44
Name: count, dtype: int64

bring_up_physical_interview
----------------------------------------

bring_up_physical_interview
Maybe    152
No       114
Yes       86
Name: count, dtype: int64

bring_up_mental_interview
----------------------------------------

bring_up_mental_interview
NaN    352
Name: count, dtype: int64

bring_up_mental_why
----------------------------------------

bring_up_mental_why
NaN                                                                                                                                                                                      82
If it impacts work I would bring it up                                                                                                                                                    1
I do not trust that the potential employer would remain unbiased in light of such information.                                                                                            1
It depends on its applicability to my job and how detrimental it could be.                                                                                                                1
discrimination/bias                                                                                                                                                                       1
                                                                                                                                                                                         ..
I do not know about potential employer and his views regarding mental health issues so will not take a chance in start but gradually will inform him ,if mental health issues exists.     1
would depend on issue and to what degree it would effect performance and/or their perception                                                                                              1
dhdhdthhusshshshdhkhsdhsdljsdkhsdskh                                                                                                                                                      1
not comfortable                                                                                                                                                                           1
my physical health issues do not affect my ability to show up to work on time and focus during he day                                                                                     1
Name: count, Length: 271, dtype: int64

openly_identified
----------------------------------------

openly_identified
False    306
True      46
Name: count, dtype: int64

identified_affected_career
----------------------------------------

identified_affected_career
NaN      307
False     26
True      19
Name: count, dtype: int64

observed_unsupportive_response
----------------------------------------

observed_unsupportive_response
NaN    352
Name: count, dtype: int64

unsupportive_response_desc
----------------------------------------

unsupportive_response_desc
NaN                                                                                                                                                                                                                                    263
As I recall, a direct supervisor was identified as having an anxiety disorder after missing several days of work through very informal channels.                                                                                         1
judging people who went to therapy                                                                                                                                                                                                       1
I've seen people mocked for depression and for taking mental health days when it seemed detrimental to the team.                                                                                                                         1
People weren't allowed to take enough time off and supervisors were not supportive of time off for mental health                                                                                                                         1
                                                                                                                                                                                                                                      ...
I have personally witnessed the CTO of a multi-thousand person company absolutely lose his shit on the phone and scream at a woman I knew to be suffering. I deeply, deeply hate him to this day and wish him nothing but ill will.      1
my manager at my previous job scoffed at my admission to him about having ADHD: "that's something my brother had as a little kid".                                                                                                       1
No thanks                                                                                                                                                                                                                                1
Had someone tell me I needed to quit taking meds for voodoo stuff                                                                                                                                                                        1
employee was ostracized and employer discussed some details with key employees which spun up the rumor mill                                                                                                                              1
Name: count, Length: 90, dtype: int64

observed_supportive_response
----------------------------------------

observed_supportive_response
NaN    352
Name: count, dtype: int64

improvement_suggestions
----------------------------------------

improvement_suggestions
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 101
I have no idea.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       2
I think opening up more conversation around these issues and increasing awareness around mental health would help ease conversations about it                                                                                                                                                                                                                                                                                                                                                                                         1
Emphasize more on whole person health as an important goal for all. More posters or ads.                                                                                                                                                                                                                                                                                                                                                                                                                                              1
Too many people use OCD and ADHD as jokes to describe their tendency or their laziness and lack of desire to pay attention. I know there are some people who have this, but the amount of people who jokingly profess they have it (without diagnosis) make it harder for people to admit they have these things in real life. In addition, it's less of a direct tech issue than a masculine issue. Transitive property: Tech is masculine, it's not masculine to admit you have issues, therefore, you don't admit it in tech.      1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ...
Supervisors should try and break the ice with employees for such discussions so that employee gets the comfort to share his issues with his manager.                                                                                                                                                                                                                                                                                                                                                                                  1
IDK                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
sdsdsdsdsdsd                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
raise awareness                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
reduce stigma. offer options for part time work. not use an EAP as their only mental health coverage.                                                                                                                                                                                                                                                                                                                                                                                                                                 1
Name: count, Length: 251, dtype: int64

additional_comments
----------------------------------------

additional_comments
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                          263
No                                                                                                                                                                                                                                                                                                                                                                                                                                                             5
Nothing                                                                                                                                                                                                                                                                                                                                                                                                                                                        3
.                                                                                                                                                                                                                                                                                                                                                                                                                                                              3
Nope                                                                                                                                                                                                                                                                                                                                                                                                                                                           2
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...
Make the previous reports available to public and suggest techniques for workspace stress revieling actions                                                                                                                                                                                                                                                                                                                                                    1
I answered using your “disordered = doctor diagnosed” so I said no to some questions. But I surely have “mental health issues” and would have answered yes to those questions. But you only asked about diagnoses disorders. You are leaving out a big pool of folks like me who just want go see the doctor or mental help professional.                                                                                                                      1
reasons for mental health issues should be covered                                                                                                                                                                                                                                                                                                                                                                                                             1
sdsdsdsdsdsd                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
I've had to drive all of the progress in mental health insurance coverage at my workplace. Before I joined they only offer short term EAP help (designed for grief or a stressful event), and did not offer coverage for an ongoing mental illness. My office visit was in network if I saw a doctor without a MH specialty to prescribe my medication, but was out-of network if I saw a psychiatrist or other provider who specialized in mental health      1
Name: count, Length: 80, dtype: int64

gender
----------------------------------------

gender
Male                                   144
male                                    52
Female                                  51
female                                  27
M                                       15
F                                        9
m                                        8
NaN                                      7
Woman                                    4
f                                        3
Non-binary                               2
agender                                  2
Let's keep it simple and say "male"      1
Identify as male                         1
Non binary                               1
Masculine                                1
Cishet male                              1
Female-identified                        1
woman                                    1
Nonbinary                                1
Man                                      1
Questioning                              1
cis male                                 1
Cis Male                                 1
I have a penis                           1
rr                                       1
cis woman                                1
Agender trans woman                      1
femmina                                  1
43                                       1
Trans man                                1
man                                      1
masculino                                1
I am a Wookie                            1
Make                                     1
Trans non-binary/genderfluid             1
CIS Male                                 1
Non-binary and gender fluid              1
Femile                                   1
Female (cis)                             1
Name: count, dtype: int64

country_live
----------------------------------------

country_live
NaN    352
Name: count, dtype: int64

state_live
----------------------------------------

state_live
NaN    352
Name: count, dtype: int64

race
----------------------------------------

race
White                         173
NaN                           148
Asian                           9
More than one of the above      8
I prefer not to answer          6
Black or African American       4
Hispanic                        1
White Hispanic                  1
European American               1
Caucasian                       1
Name: count, dtype: int64

country_work
----------------------------------------

country_work
NaN    352
Name: count, dtype: int64

state_work
----------------------------------------

state_work
NaN    352
Name: count, dtype: int64

====================================================================================================
SURVEY YEAR : 2020
====================================================================================================


self_employed
----------------------------------------

self_employed
NaN    180
Name: count, dtype: int64

no_employees
----------------------------------------

no_employees
More than 1000    72
26-100            28
NaN               25
100-500           24
500-1000          20
6-25              10
1-5                1
Name: count, dtype: int64

tech_company
----------------------------------------

tech_company
1.0    97
0.0    58
NaN    25
Name: count, dtype: int64

primary_role_tech
----------------------------------------

primary_role_tech
1.0    141
NaN     25
0.0     14
Name: count, dtype: int64

benefits
----------------------------------------

benefits
Yes                               64
I don't know                      50
No                                35
NaN                               25
Not eligible for coverage / NA     6
Name: count, dtype: int64

know_options
----------------------------------------

know_options
No     84
Yes    49
NaN    47
Name: count, dtype: int64

formal_discussion
----------------------------------------

formal_discussion
No              76
Yes             66
NaN             25
I don't know    13
Name: count, dtype: int64

resources
----------------------------------------

resources
No              69
Yes             55
I don't know    31
NaN             25
Name: count, dtype: int64

anonymity
----------------------------------------

anonymity
I don't know    87
Yes             53
NaN             25
No              15
Name: count, dtype: int64

leave_ease
----------------------------------------

leave_ease
Somewhat easy                 44
Very easy                     30
NaN                           25
Difficult                     23
Somewhat difficult            20
I don't know                  20
Neither easy nor difficult    18
Name: count, dtype: int64

comfort_physical_mental
----------------------------------------

comfort_physical_mental
Physical health                   115
Same level of comfort for each     34
NaN                                25
Mental health                       6
Name: count, dtype: int64

comfort_supervisor
----------------------------------------

comfort_supervisor
No       64
Maybe    50
Yes      41
NaN      25
Name: count, dtype: int64

discussed_with_employer
----------------------------------------

discussed_with_employer
0.0    115
1.0     40
NaN     25
Name: count, dtype: int64

comfort_coworkers
----------------------------------------

comfort_coworkers
Maybe    66
No       56
Yes      33
NaN      25
Name: count, dtype: int64

discussed_with_coworkers
----------------------------------------

discussed_with_coworkers
0.0    88
1.0    67
NaN    25
Name: count, dtype: int64

coworker_discussed_with_you
----------------------------------------

coworker_discussed_with_you
0.0    88
1.0    66
NaN    26
Name: count, dtype: int64

coverage_mental_health
----------------------------------------

coverage_mental_health
NaN    155
1.0     15
0.0     10
Name: count, dtype: int64

know_resources
----------------------------------------

know_resources
NaN                     155
Yes, I know several      11
No, I don't know any      7
I know some               7
Name: count, dtype: int64

reveal_to_clients
----------------------------------------

reveal_to_clients
NaN                                          155
No, because it would impact me negatively     12
No, because it doesn't matter                  6
Yes, always                                    3
Not applicable to me                           3
Sometimes, if it comes up                      1
Name: count, dtype: int64

reveal_to_coworkers
----------------------------------------

reveal_to_coworkers
NaN                                          155
No, because it would impact me negatively     10
No, because it doesn't matter                  5
Not applicable to me                           5
Yes, always                                    4
Sometimes, if it comes up                      1
Name: count, dtype: int64

productivity_affected
----------------------------------------

productivity_affected
NaN                     155
Yes                      20
Unsure                    4
Not applicable to me      1
Name: count, dtype: int64

productivity_percent_affected
----------------------------------------

productivity_percent_affected
NaN        160
1-25%        7
26-50%       7
76-100%      5
51-75%       1
Name: count, dtype: int64

prev_tech_company
----------------------------------------

prev_tech_company
1.0    82
0.0    53
NaN    45
Name: count, dtype: int64

prev_benefits
----------------------------------------

prev_benefits
No, none did         51
NaN                  45
Some did             44
I don't know         24
Yes, they all did    16
Name: count, dtype: int64

prev_know_options
----------------------------------------

prev_know_options
NaN                                45
N/A (was not aware)                39
I was aware of some                37
N/A (none offered)                 31
Yes, I was aware of all of them    14
No, I only became aware later      14
Name: count, dtype: int64

prev_formal_discussion
----------------------------------------

prev_formal_discussion
None did             83
NaN                  45
Some did             37
I don't know          8
Yes, they all did     7
Name: count, dtype: int64

prev_resources
----------------------------------------

prev_resources
None did             84
NaN                  45
Some did             38
Yes, they all did    13
Name: count, dtype: int64

prev_anonymity
----------------------------------------

prev_anonymity
I don't know    75
NaN             45
Yes, always     27
No              17
Sometimes       16
Name: count, dtype: int64

prev_comfort_physical_mental
----------------------------------------

prev_comfort_physical_mental
Physical health                   104
NaN                                45
Same level of comfort for each     27
Mental health                       4
Name: count, dtype: int64

prev_comfort_supervisor
----------------------------------------

prev_comfort_supervisor
No, none of my previous supervisors    61
Some of my previous supervisors        55
NaN                                    45
Yes, all of my previous supervisors    10
I don't know                            9
Name: count, dtype: int64

prev_discussed_with_employer
----------------------------------------

prev_discussed_with_employer
0.0    103
NaN     45
1.0     32
Name: count, dtype: int64

prev_comfort_coworkers
----------------------------------------

prev_comfort_coworkers
At some of my previous employers        64
No, at none of my previous employers    57
NaN                                     45
Yes, at all of my previous employers    14
Name: count, dtype: int64

prev_discussed_with_coworkers
----------------------------------------

prev_discussed_with_coworkers
0.0    87
NaN    47
1.0    46
Name: count, dtype: int64

currently_disordered
----------------------------------------

currently_disordered
NaN    180
Name: count, dtype: int64

diagnosed_disorder
----------------------------------------

diagnosed_disorder
NaN    180
Name: count, dtype: int64

past_disorder
----------------------------------------

past_disorder
No            65
Yes           62
Possibly      34
Don't Know    15
NaN            4
Name: count, dtype: int64

sought_treatment
----------------------------------------

sought_treatment
0    98
1    82
Name: count, dtype: int64

family_history
----------------------------------------

family_history
No              88
Yes             58
I don't know    34
Name: count, dtype: int64

interference_when_treated
----------------------------------------

interference_when_treated
NaN    180
Name: count, dtype: int64

interference_when_not_treated
----------------------------------------

interference_when_not_treated
NaN    180
Name: count, dtype: int64

observations_less_likely_reveal
----------------------------------------

observations_less_likely_reveal
No       69
Maybe    41
NaN      36
Yes      34
Name: count, dtype: int64

bring_up_physical_interview
----------------------------------------

bring_up_physical_interview
Maybe    69
Yes      58
No       53
Name: count, dtype: int64

bring_up_mental_interview
----------------------------------------

bring_up_mental_interview
NaN    180
Name: count, dtype: int64

bring_up_mental_why
----------------------------------------

bring_up_mental_why
NaN                                                                                                                                                             31
It depend on if the discussion would have an impact on my employment                                                                                             1
It affects my employment or job                                                                                                                                  1
it will affect another person                                                                                                                                    1
gryry                                                                                                                                                            1
                                                                                                                                                                ..
Since it involves a potential chance of losing the offer                                                                                                         1
No new employer would care about our issues. They have a choice to select someone else.                                                                          1
I don't wish to discuss physical health issues that are not relevant to the job                                                                                  1
uncomfortable. if I felt that my health was going to be an issue I would not apply or would retract my application.                                              1
If it is a part of me, then I would want to share that during the interview. If I wouldn't it could also be perceived as not being honest with the employer.     1
Name: count, Length: 150, dtype: int64

openly_identified
----------------------------------------

openly_identified
0    154
1     26
Name: count, dtype: int64

identified_affected_career
----------------------------------------

identified_affected_career
NaN    155
1.0     15
0.0     10
Name: count, dtype: int64

observed_unsupportive_response
----------------------------------------

observed_unsupportive_response
NaN    180
Name: count, dtype: int64

unsupportive_response_desc
----------------------------------------

unsupportive_response_desc
NaN                                                                                                                                                                                                                                                                                                                                                                                                                              131
na                                                                                                                                                                                                                                                                                                                                                                                                                                 2
Some times with my boss, he will response properly it affects work and my mental state.                                                                                                                                                                                                                                                                                                                                            1
taking less to that person or ignorance                                                                                                                                                                                                                                                                                                                                                                                            1
thyu                                                                                                                                                                                                                                                                                                                                                                                                                               1
My friend who was fired because of a mental health induced outburst.                                                                                                                                                                                                                                                                                                                                                               1
I was basically told to hang in there by coworkers when I broke up and broke down. (Though one did share a very personal story with me.) In other instances I was just told to see HR where I was handed a list of counselors.                                                                                                                                                                                                     1
sdfsdf                                                                                                                                                                                                                                                                                                                                                                                                                             1
fsdf                                                                                                                                                                                                                                                                                                                                                                                                                               1
People criticised the manager for not telling them about the colleague's condition. But the manager was bound by confidentiality, and explained that others would not like it if the manager discussed their personal lives. I quite understood this, but there was nevertheless tension over the matter.                                                                                                                          1
Being called lazy, and and criticized                                                                                                                                                                                                                                                                                                                                                                                              1
they made fun of my mental condition                                                                                                                                                                                                                                                                                                                                                                                               1
I'd rather not.                                                                                                                                                                                                                                                                                                                                                                                                                    1
underestimating impact to me.                                                                                                                                                                                                                                                                                                                                                                                                      1
Negatively treated                                                                                                                                                                                                                                                                                                                                                                                                                 1
when stressed out and asked for leave as we were going through extending shift hours, leave was denied                                                                                                                                                                                                                                                                                                                             1
I was promoted from engineer to engineering manager and the role was not well defined. I asked for help and feedback because I didn't know whether I was being effective or not and did not receive any help. This made my job very difficult, and went from being the #1 evaluated employee in the department as an engineer, to a very poor evaluation a year later. I am no longer an engineering manager and was demoted.      1
I once had an autistic coworker and people seemed to make fun of him a bit behind his back, but were nonetheless polite and supportive to him. However, as it became apparent that he was unable to perform any teamwork an struggled with his duties, people started avoiding him and be less supportive until he was laid off the company.                                                                                       1
Denying mental health disclosures to open a Incapacity Investigation, which led to retrenchment / severance when offered a chance to take the necessary tests.                                                                                                                                                                                                                                                                     1
I've observed coworkers making negative comments about another coworker due to his sometimes erratic mood, which I know to be due to his mental health issues.                                                                                                                                                                                                                                                                     1
Preconception.                                                                                                                                                                                                                                                                                                                                                                                                                     1
Situations indicating mental health issues interpreted as laziness                                                                                                                                                                                                                                                                                                                                                                 1
There's a lot of negativity at my current job. A lot of elitism. Showing vulnerability is a sign of weakness unfortunately. It is not only regarding mental ilness. Even lack of knowledge is enough. It's getting to be a culture since lack of leadership that can help with a better work place.                                                                                                                                1
When I needed accommodations and asked, I felt belittled and humiliated. I left the company within a week after their not granting them to me and making me feel awful.                                                                                                                                                                                                                                                            1
People make the person relize that again and again that he is suffering. And at the back lot of gossip happens. That person will not get good project, pay hike etc or may be put on PIP                                                                                                                                                                                                                                           1
Person was put on a PIP and eventually fired.                                                                                                                                                                                                                                                                                                                                                                                      1
After discussion of mental health issues there was gossiping about the coworker in question.                                                                                                                                                                                                                                                                                                                                       1
They just ignored the situation by increasing pressure and stress at work.                                                                                                                                                                                                                                                                                                                                                         1
Prefer not to.                                                                                                                                                                                                                                                                                                                                                                                                                     1
dont know                                                                                                                                                                                                                                                                                                                                                                                                                          1
A Staff member was an Alcoholic and was drinking at work. The staff starting talking about her behind her back, did not bring the correct staff in to handle the request.                                                                                                                                                                                                                                                          1
Had a panic attack,explained it was a panic attack but ambulance still called for "insurance" reasons                                                                                                                                                                                                                                                                                                                              1
People unwilling to understand a need for compromising day-to-day procedure to accommodate mental health needs.                                                                                                                                                                                                                                                                                                                    1
Made fun behind their backs                                                                                                                                                                                                                                                                                                                                                                                                        1
I was treated unfair, like a child.                                                                                                                                                                                                                                                                                                                                                                                                1
A colleague was fired during his probation period, because he was off for some days and openly spoke about his mental health issues. I left that employee some months after...                                                                                                                                                                                                                                                     1
Cannot discuss due to pending litigation. I no longer work there.                                                                                                                                                                                                                                                                                                                                                                  1
Coworkers spoke poorly about the person                                                                                                                                                                                                                                                                                                                                                                                            1
The director was mobbing and made one of my coworkers quit                                                                                                                                                                                                                                                                                                                                                                         1
Yes                                                                                                                                                                                                                                                                                                                                                                                                                                1
Pass                                                                                                                                                                                                                                                                                                                                                                                                                               1
I think it was more they just didn't take what they were going through seriously.                                                                                                                                                                                                                                                                                                                                                  1
Mentioned earlier, previous supervisor dismissed conversation                                                                                                                                                                                                                                                                                                                                                                      1
.                                                                                                                                                                                                                                                                                                                                                                                                                                  1
some put under stress                                                                                                                                                                                                                                                                                                                                                                                                              1
A colleague being managed out of the organisation because of his depression                                                                                                                                                                                                                                                                                                                                                        1
He had been relieved from work earlier than usual.                                                                                                                                                                                                                                                                                                                                                                                 1

observed_supportive_response
----------------------------------------

observed_supportive_response
NaN    180
Name: count, dtype: int64

improvement_suggestions
----------------------------------------

improvement_suggestions
NaN                                                                                                                                                                                                                                                                                                                                           45
They should understand and we should talk openely                                                                                                                                                                                                                                                                                              1
behaving well with them and give them a good time for there task to complete. give them time to complete the task.                                                                                                                                                                                                                             1
thyt                                                                                                                                                                                                                                                                                                                                           1
Mental health counseling should be provided as a default part of all employment, not just provided as an option.                                                                                                                                                                                                                               1
                                                                                                                                                                                                                                                                                                                                              ..
Openly brief their support level on the joining day and encourage employee to open up time to time.                                                                                                                                                                                                                                            1
Big tech giants need to more, openly and encourage all to do their part. Just like some companies select vendors who may be doing some Go Green initiatives, or awarding to minority owned businesses, they can also award businesses that does their part in this mental health area. In other words, encourage, directly and indirectly.     1
Make it Mental Health policies part of onboarding.                                                                                                                                                                                                                                                                                             1
easier ways to get time off; ability to work from home as needed                                                                                                                                                                                                                                                                               1
The first thing is to make any person on what level in the company feeling safe to open up about the issues the person is facing. In the teams I've been working at our current company we do try to make the team as safe as possible so that anybody will be able to open up and discuss the issues they're facing.                          1
Name: count, Length: 136, dtype: int64

additional_comments
----------------------------------------

additional_comments
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            110
no                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              11
No                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              10
na                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               3
Nothing                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          3
mental health should be a law by government.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
ryry                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             1
family background, and personal responsibilites                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1
The society of tech workers contains well-entrenched cultures of denial of the value of mental health awareness and treatment that must be addressed. Some of these cultures are truly destructive and violent. Some are even encouraged by business and political actors.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
I'm not sure right now.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
safs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             1
as                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
No.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1
For example, if a person sought out help, you could ask if the person took the treatment, and why(or why not).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
nn                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
Inform in advance how much time it will take for the survey and educate on the mental illness. We face stress and pressure in project and their deadlines. not sure how to face them.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
HOW ANONYMOUS IS A COMPANY WHEN TREATING MENTAL ILLNESS WE ARE NOT CONFIDENT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
How is society treating one with mental illness in respondents point if view is what could have been included                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1
I want to help, I want to advocate, but I'm scared doing so will hurt my career.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
N/a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1
No comment                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
IT-workers prefer to work in the dark. But sunlight is essential due to a healthy body. Is there a solution? (offices out of glas, open, sunny rooms for breaks etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
Nothing to add.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1

gender
----------------------------------------

gender
Male               71
male               32
Female             25
female             21
F                   9
M                   5
m                   4
f                   3
NaN                 2
Woman               2
mail                1
FEMALE              1
female, she/her     1
mostly male         1
cisgender male      1
MAle                1
Name: count, dtype: int64

country_live
----------------------------------------

country_live
NaN    180
Name: count, dtype: int64

state_live
----------------------------------------

state_live
NaN    180
Name: count, dtype: int64

race
----------------------------------------

race
NaN                           116
White                          48
Asian                          13
More than one of the above      1
I prefer not to answer          1
Black or African American       1
Name: count, dtype: int64

country_work
----------------------------------------

country_work
NaN    180
Name: count, dtype: int64

state_work
----------------------------------------

state_work
NaN    180
Name: count, dtype: int64

====================================================================================================
SURVEY YEAR : 2021
====================================================================================================


self_employed
----------------------------------------

self_employed
NaN    131
Name: count, dtype: int64

no_employees
----------------------------------------

no_employees
More than 1000    48
100-500           22
26-100            20
NaN               17
6-25              11
500-1000           9
1-5                4
Name: count, dtype: int64

tech_company
----------------------------------------

tech_company
1.0    75
0.0    39
NaN    17
Name: count, dtype: int64

primary_role_tech
----------------------------------------

primary_role_tech
1.0    99
NaN    17
0.0    15
Name: count, dtype: int64

benefits
----------------------------------------

benefits
Yes                               54
No                                30
I don't know                      27
NaN                               17
Not eligible for coverage / NA     3
Name: count, dtype: int64

know_options
----------------------------------------

know_options
No     58
Yes    45
NaN    28
Name: count, dtype: int64

formal_discussion
----------------------------------------

formal_discussion
No              58
Yes             46
NaN             17
I don't know    10
Name: count, dtype: int64

resources
----------------------------------------

resources
No              50
Yes             46
I don't know    18
NaN             17
Name: count, dtype: int64

anonymity
----------------------------------------

anonymity
I don't know    57
Yes             47
NaN             17
No              10
Name: count, dtype: int64

leave_ease
----------------------------------------

leave_ease
Very easy                     27
Somewhat easy                 25
Somewhat difficult            21
NaN                           17
I don't know                  15
Neither easy nor difficult    15
Difficult                     11
Name: count, dtype: int64

comfort_physical_mental
----------------------------------------

comfort_physical_mental
Physical health                   71
Same level of comfort for each    40
NaN                               17
Mental health                      3
Name: count, dtype: int64

comfort_supervisor
----------------------------------------

comfort_supervisor
No       44
Yes      36
Maybe    34
NaN      17
Name: count, dtype: int64

discussed_with_employer
----------------------------------------

discussed_with_employer
0.0    86
1.0    28
NaN    17
Name: count, dtype: int64

comfort_coworkers
----------------------------------------

comfort_coworkers
Maybe    43
No       36
Yes      35
NaN      17
Name: count, dtype: int64

discussed_with_coworkers
----------------------------------------

discussed_with_coworkers
0.0    68
1.0    45
NaN    18
Name: count, dtype: int64

coworker_discussed_with_you
----------------------------------------

coworker_discussed_with_you
0.0    63
1.0    50
NaN    18
Name: count, dtype: int64

coverage_mental_health
----------------------------------------

coverage_mental_health
NaN    114
0.0     10
1.0      7
Name: count, dtype: int64

know_resources
----------------------------------------

know_resources
NaN                     114
No, I don't know any      7
I know some               6
Yes, I know several       4
Name: count, dtype: int64

reveal_to_clients
----------------------------------------

reveal_to_clients
NaN                                          114
No, because it doesn't matter                  6
No, because it would impact me negatively      5
Sometimes, if it comes up                      2
Yes, always                                    2
Not applicable to me                           2
Name: count, dtype: int64

reveal_to_coworkers
----------------------------------------

reveal_to_coworkers
NaN                                          114
No, because it would impact me negatively      6
No, because it doesn't matter                  4
Not applicable to me                           4
Yes, always                                    2
Sometimes, if it comes up                      1
Name: count, dtype: int64

productivity_affected
----------------------------------------

productivity_affected
NaN                     114
Yes                      11
No                        3
Not applicable to me      2
Unsure                    1
Name: count, dtype: int64

productivity_percent_affected
----------------------------------------

productivity_percent_affected
NaN       120
26-50%      5
1-25%       4
51-75%      2
Name: count, dtype: int64

prev_tech_company
----------------------------------------

prev_tech_company
1.0    53
NaN    46
0.0    32
Name: count, dtype: int64

prev_benefits
----------------------------------------

prev_benefits
NaN                  46
No, none did         31
Some did             19
Yes, they all did    18
I don't know         17
Name: count, dtype: int64

prev_know_options
----------------------------------------

prev_know_options
NaN                                46
N/A (none offered)                 25
I was aware of some                22
N/A (was not aware)                19
Yes, I was aware of all of them    14
No, I only became aware later       5
Name: count, dtype: int64

prev_formal_discussion
----------------------------------------

prev_formal_discussion
None did             51
NaN                  46
Some did             19
I don't know          9
Yes, they all did     6
Name: count, dtype: int64

prev_resources
----------------------------------------

prev_resources
None did             51
NaN                  46
Some did             24
Yes, they all did    10
Name: count, dtype: int64

prev_anonymity
----------------------------------------

prev_anonymity
I don't know    50
NaN             46
Yes, always     16
No              11
Sometimes        8
Name: count, dtype: int64

prev_comfort_physical_mental
----------------------------------------

prev_comfort_physical_mental
Physical health                   63
NaN                               46
Same level of comfort for each    20
Mental health                      2
Name: count, dtype: int64

prev_comfort_supervisor
----------------------------------------

prev_comfort_supervisor
NaN                                    46
No, none of my previous supervisors    39
Some of my previous supervisors        31
Yes, all of my previous supervisors    10
I don't know                            5
Name: count, dtype: int64

prev_discussed_with_employer
----------------------------------------

prev_discussed_with_employer
0.0    65
NaN    46
1.0    20
Name: count, dtype: int64

prev_comfort_coworkers
----------------------------------------

prev_comfort_coworkers
NaN                                     46
No, at none of my previous employers    37
At some of my previous employers        31
Yes, at all of my previous employers    17
Name: count, dtype: int64

prev_discussed_with_coworkers
----------------------------------------

prev_discussed_with_coworkers
0.0    49
NaN    48
1.0    34
Name: count, dtype: int64

currently_disordered
----------------------------------------

currently_disordered
NaN    131
Name: count, dtype: int64

diagnosed_disorder
----------------------------------------

diagnosed_disorder
NaN    131
Name: count, dtype: int64

past_disorder
----------------------------------------

past_disorder
No            48
Yes           39
Possibly      24
Don't Know    16
NaN            4
Name: count, dtype: int64

sought_treatment
----------------------------------------

sought_treatment
0    67
1    64
Name: count, dtype: int64

family_history
----------------------------------------

family_history
No              59
Yes             52
I don't know    20
Name: count, dtype: int64

interference_when_treated
----------------------------------------

interference_when_treated
NaN    131
Name: count, dtype: int64

interference_when_not_treated
----------------------------------------

interference_when_not_treated
NaN    131
Name: count, dtype: int64

observations_less_likely_reveal
----------------------------------------

observations_less_likely_reveal
No       46
Maybe    32
Yes      28
NaN      25
Name: count, dtype: int64

bring_up_physical_interview
----------------------------------------

bring_up_physical_interview
Maybe    54
No       44
Yes      33
Name: count, dtype: int64

bring_up_mental_interview
----------------------------------------

bring_up_mental_interview
NaN    131
Name: count, dtype: int64

bring_up_mental_why
----------------------------------------

bring_up_mental_why
NaN                                                                                                                                                                                                                                                                39
physical health issues often are not stigmatized/held against you                                                                                                                                                                                                   1
if it doesn't affect my ability to do the job                                                                                                                                                                                                                       1
uikjgiu                                                                                                                                                                                                                                                             1
Assumptions                                                                                                                                                                                                                                                         1
                                                                                                                                                                                                                                                                   ..
Not sure if it is relevant to the job                                                                                                                                                                                                                               1
Of course, if we are talking about a physical health issue which is going to affect my work, I would bring, but if we are talking about, let's say, diabetes (and I have it under control) I cannot see any reasons for bring it to discussion in an interview.     1
If can affect by future work and don't know how employee will react to these info                                                                                                                                                                                   1
It will impact on the job                                                                                                                                                                                                                                           1
Luckily we have social security civered under the law so it's normal.                                                                                                                                                                                               1
Name: count, Length: 93, dtype: int64

openly_identified
----------------------------------------

openly_identified
0    114
1     17
Name: count, dtype: int64

identified_affected_career
----------------------------------------

identified_affected_career
NaN    114
0.0     10
1.0      7
Name: count, dtype: int64

observed_unsupportive_response
----------------------------------------

observed_unsupportive_response
NaN    131
Name: count, dtype: int64

unsupportive_response_desc
----------------------------------------

unsupportive_response_desc
NaN                                                                                                                                                                                                                                                                                                                                                                                                                       112
I saw a coworker be ostracized from a company because of their mental health issue.                                                                                                                                                                                                                                                                                                                                         1
I was told I did not have mental health issues                                                                                                                                                                                                                                                                                                                                                                              1
A woman committed herself to a state hospital for a few days. The entire office discussed it. I felt awful for her.                                                                                                                                                                                                                                                                                                         1
Friends have bailed on me after sharing this                                                                                                                                                                                                                                                                                                                                                                                1
A couple previous employers weren't accommodating to my need to have a more flexible schedule or work location, or failed to understand that I'm not being lazy when I'm in the midst of a depressive episode.                                                                                                                                                                                                              1
no idea                                                                                                                                                                                                                                                                                                                                                                                                                     1
3 weeks ago i was unjustly fired and will be filing a complaint with the EEOC, if not also hiring an attorney to pursue damages for wrongful termination and discrimination                                                                                                                                                                                                                                                 1
Judgment, decrease in trust/respect                                                                                                                                                                                                                                                                                                                                                                                         1
Getting disgusted looks and people talking shit behind my back for having scars visible due to short sleeved shirts on my arms during hot days :(                                                                                                                                                                                                                                                                           1
A former coworker experienced a mental health crisis and instead of being offered time off and the appropriate help, he was fired.                                                                                                                                                                                                                                                                                          1
I have seen in numerous occasions how someone who says they feel overwhelmed by the amount of work and no change is made, and sometimes more work is given to them.                                                                                                                                                                                                                                                         1
There are people who have been depressed, but deadlines are deadlines. Sometimes people got extensions and we expressed sympathy, but nobody was interested in changing the environment to make it less stressful.                                                                                                                                                                                                          1
BLM                                                                                                                                                                                                                                                                                                                                                                                                                         1
Gossip and outright offensive comments                                                                                                                                                                                                                                                                                                                                                                                      1
Just hearing of other people not being accommodated when they've shared.                                                                                                                                                                                                                                                                                                                                                    1
In my previous job the employer was not affected when confronted with facts supporting that indeed there was too much pressure                                                                                                                                                                                                                                                                                              1
Previous job - leadership mocking the individual                                                                                                                                                                                                                                                                                                                                                                            1
During pair programming I could notice some condescending behaviour from one of my peers. We were doing something he was used to do and he was acting as I was supposed to know what to do. I got really anxious at that point, he noticed and proceeded with the approach. It was a really bad experience, it took me a few weeks to get rid of that feeling and stop repeating that moment in my head, compulsively.      1
They put more pressure to them and ultimately fired them...                                                                                                                                                                                                                                                                                                                                                                 1
Name: count, dtype: int64

observed_supportive_response
----------------------------------------

observed_supportive_response
NaN    131
Name: count, dtype: int64

improvement_suggestions
----------------------------------------

improvement_suggestions
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 42
discuss the topic openly                                                                                                                                                                                                                                                                                                                                                                                                                                                                             1
lk                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
Empathy Training                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
no comment                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ..
Encourage use of tools that have been proven effective like yoga, mindfulness, etc with a programs to pay for membership to apps/classes. Tackle work life balance. I'm at 75-90 hours a week and it's hard on family.                                                                                                                                                                                                                                                                               1
Talk withe employees, and create a positive environment                                                                                                                                                                                                                                                                                                                                                                                                                                              1
Offer or let folks know that there are mental health benefits available and how to access them                                                                                                                                                                                                                                                                                                                                                                                                       1
It seems to me that bad management makes a huge impact on people's mental health. It is where all the unnecessary pressure starts, the unnecessary short deadlines, the frequent change of priority. I think having the industry pacing down, respecting the processes, and giving people reasonable deadlines, would make a great difference. Other than that, a more humane HR, open channels for discussing mental health and more flexible vacation/sick days would represent a good change.     1
Support them , and provide less stress time for work                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
Name: count, Length: 90, dtype: int64

additional_comments
----------------------------------------

additional_comments
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   89
j                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
More folks need to talk about unrealistic expectations in the workplace.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
I am wondering how responses changed due to COVID                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
I don't have anything else to share.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
more questions covering fun oriented environment in the workplace to overcome this weakness of mental stress among the working people                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1
dsd                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1
Having done a few other jobs outside of the tech industry, mostly in the tutoring/physical activity instructor sphere, Engineering seems particularly challenging for those suffering from a mental illness. The irregularity can be disorienting as some days you're able to do your job just fine, and others you can feel completely paralyzed and anxious that if anyone found out, you'd be outed as a bad engineer. It compounds the imposter syndrome I feel as a woman in stem.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
..                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
nothing else                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
nothing. Thanks                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
nil                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1
some questions could have used an "i don't know" when they weren't offered.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
Nope                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
Maybe it is interesting to ask the career status - fresh in the job, some experience, 20+ years. To check for "survior ship bias" of senior personal in answering those questions. E. g. only people who are verry resilient stay in this industry long enough, who are not aware of the colleagues that got "lost" on the way due to mental health issues.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
Please consider offering a way for people to report on their employer's efficacy in handling mental health issues in things like glassdoor, etc                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
I spend a fair amount of time in the workplace fearing stigma because of my mental illness. I struggle as it is, some days, and I fear people would use it against me.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
na                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1

gender
----------------------------------------

gender
Male                  41
Female                29
male                  18
female                15
woman                  4
F                      3
m                      3
f                      2
NaN                    2
M                      2
afab non-binary        1
MALE                   1
Masculine              1
Female (cis)           1
b                      1
male/he/him            1
homem cis              1
FEMALE                 1
cis-het male           1
cis male               1
Non-binary             1
Non-binary/Agender     1
Name: count, dtype: int64

country_live
----------------------------------------

country_live
NaN    131
Name: count, dtype: int64

state_live
----------------------------------------

state_live
NaN    131
Name: count, dtype: int64

race
----------------------------------------

race
NaN                           82
White                         35
Asian                         11
Black or African American      2
More than one of the above     1
Name: count, dtype: int64

country_work
----------------------------------------

country_work
NaN    131
Name: count, dtype: int64

state_work
----------------------------------------

state_work
NaN    131
Name: count, dtype: int64

## General Harmonization Rules

Some inconsistencies appear across multiple survey years.

These are standardized using common mapping dictionaries.

In [7]:
binary_map = {

    "yes":"Yes",
    "Yes":"Yes",
    "YES":"Yes",

    "true":"Yes",
    "True":"Yes",

    "1":"Yes",
    "1.0":"Yes",

    "no":"No",
    "No":"No",
    "NO":"No",

    "false":"No",
    "False":"No",

    "0":"No",
    "0.0":"No"
}

In [8]:
binary_map = {

    "Yes": "Yes",
    "yes": "Yes",
    "YES": "Yes",

    "True": "Yes",
    "true": "Yes",
    True: "Yes",

    "1": "Yes",
    "1.0": "Yes",
    1: "Yes",
    1.0: "Yes",

    "No": "No",
    "no": "No",
    "NO": "No",

    "False": "No",
    "false": "No",
    False: "No",

    "0": "No",
    "0.0": "No",
    0: "No",
    0.0: "No"
}

binary_columns = [

    "self_employed",
    "tech_company",
    "primary_role_tech",
    "sought_treatment",

    "discussed_with_employer",
    "discussed_with_coworkers",
    "coworker_discussed_with_you",

    "coverage_mental_health",

    "prev_tech_company",
    "prev_discussed_with_employer",
    "prev_discussed_with_coworkers",

    "openly_identified",
    "identified_affected_career"
]

for col in binary_columns:

    if col in df.columns:

        df[col] = (
            df[col]
            .replace(binary_map)
        )

## Standardize "Don't Know" Responses

Different survey years recorded uncertain responses using slightly different wording.

These responses are standardized to a single category.

In [9]:
dontknow_map = {

    "Don't know": "Don't Know",
    "Don't Know": "Don't Know",
    "I don't know": "Don't Know",
    "Dont know": "Don't Know",
    "Not sure": "Don't Know",
    "Unsure": "Don't Know"
}

dontknow_columns = [

    "benefits",
    "know_options",
    "formal_discussion",
    "resources",
    "anonymity",
    "leave_ease",

    "family_history",

    "currently_disordered",
    "past_disorder",

    "prev_benefits",
    "prev_formal_discussion",
    "prev_resources",
    "prev_anonymity",
    "prev_comfort_supervisor"
]

for col in dontknow_columns:

    if col in df.columns:

        df[col] = df[col].replace(dontknow_map)

## Harmonize Gender

The gender variable contains a large number of synonymous responses, spelling variations, abbreviations, and free-text entries.

To improve interpretability while preserving meaningful distinctions, responses are grouped into four categories:

- Male
- Female
- Other
- Unknown

In [11]:
# Gender Mapping
gender_map = {

    # Male
    "male": "Male",
    "m": "Male",
    "man": "Male",
    "cis male": "Male",
    "cis-male": "Male",
    "cisgender male": "Male",
    "male (cis)": "Male",
    "male-ish": "Male",
    "mail": "Male",
    "malel": "Male",
    "masculine": "Male",
    "identify as male": "Male",
    "cishet male": "Male",
    "make": "Male",
    "dude": "Male",
    "i have a penis": "Male",
    "man?": "Male", 
    "male (cisgender)": "Male",  
    "male (trans)": "Male",  
    
    # Female
    "female": "Female",
    "f": "Female",
    "woman": "Female",
    "cis female": "Female",
    "cis-female": "Female",
    "cisgender female": "Female",
    "female (cis)": "Female",
    "female (cisgender)": "Female",
    "female-identified": "Female",
    "femail": "Female",
    "femalw": "Female",
    "femile": "Female",
    "woman?": "Female",  
}

# Apply the mapping with a fallback to "Other"
def clean_gender(val):
    if pd.isna(val):
        return "Unknown"
    
    # Convert to string, strip, lowercase
    val = str(val).strip().lower()
    
    # Return mapped value, or "Other" if not found
    return gender_map.get(val, "Other")

# Apply to the dataframe
df["gender"] = df["gender"].apply(clean_gender)

# Check the results
print(df["gender"].value_counts())

gender
Unknown    1275
Male       1176
Female      551
Other        80
Name: count, dtype: int64

## Harmonize Country Names

Country names are standardized to eliminate duplicate categories caused by abbreviations and alternate naming conventions.

In [12]:
country_map = {

    "united states of america":"United States",
    "united states":"United States",
    "usa":"United States",
    "us":"United States",

    "uk":"United Kingdom",
    "england":"United Kingdom",
    "great britain":"United Kingdom",

    "brasil":"Brazil",

    "deutschland":"Germany"
}

country_columns = [

    "country_live",
    "country_work"
]

for col in country_columns:

    if col in df.columns:

        df[col] = (

            df[col]
              .astype("string")
              .str.strip()
              .str.lower()
              .replace(country_map)
              .str.title()

        )

## Year-Specific Harmonization

Some response options were introduced or modified in specific survey years.

These survey-specific values are harmonized individually while preserving their original meaning.

In [14]:
# 2017 onwards

mask = df["source_file"] >= 2017

df.loc[mask, "benefits"] = (

    df.loc[mask, "benefits"]

      .replace({

          "I don't know":"Don't Know",
          "Not eligible for coverage / NA":"Not Eligible"

      })

)

df.loc[mask, "leave_ease"] = (

    df.loc[mask, "leave_ease"]

      .replace({

          "Difficult":"Very Difficult"

      })

)

In [15]:
print("="*60)

print(f"Rows      : {df.shape[0]}")
print(f"Columns   : {df.shape[1]}")

print("\nDuplicate Rows")
print(df.duplicated().sum())

print("\nRemaining Missing Values")
display(df.isna().sum().sort_values(ascending=False).head(20))

print("\nUnique Categories")

summary = pd.DataFrame({
    "Unique Values": df.nunique(dropna=True),
    "Missing": df.isna().sum()
})

display(summary.sort_values("Unique Values"))

print("="*60)

============================================================
Rows      : 3082
Columns   : 70

Duplicate Rows
0

Remaining Missing Values

identified_affected_how           3000
productivity_percent_affected     2888
identified_affected_career        2860
know_resources                    2823
reveal_to_coworkers               2823
productivity_affected             2823
reveal_to_clients                 2823
coverage_mental_health            2823
unsupportive_response_desc        2678
team_reaction_if_knew             2665
willing_to_interview              2665
additional_comments               2615
diagnosed_disorder                2567
state_live                        2274
state_work                        2265
race                              1981
country_live                      1911
country_work                      1911
observed_supportive_response      1911
observed_unsupportive_response    1911
dtype: int64

Unique Categories

                            Unique Values  Missing
self_employed                           2     1854
tech_company                            2      259
primary_role_tech                       2     1505
have_prev_employers                     2     1909
prev_tech_company                       2     1536
...                                   ...      ...
country_work                           58     1911
additional_comments                   358     2615
unsupportive_response_desc            402     2678
improvement_suggestions              1236     1821
bring_up_mental_why                  1378     1680

[70 rows x 2 columns]

============================================================

In [16]:
df.to_csv(
    "../data/processed/harmonized_osmi_data.csv",
    index=False
)

print("✅ Harmonized dataset saved successfully.")

✅ Harmonized dataset saved successfully.